Nymph Game Engine: Graphics::SetUniformEvent Class Reference
Graphics::SetUniformEvent Class Reference
Class for set uniform event.
#include <set_uniform_event.h>
Public Member Functions
SetUniformEvent ()=delete
SetUniformEvent (const Uniform &uniform)
Constructor for setUniformEvent.
const Uniform getUniform () const noexcept
Gets the uniform.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
const EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr< SetUniformEvent > create (const Uniform &uniform)
Factory function for SetUniformEvent.
Detailed Description
Class for set uniform event.
Constructor & Destructor Documentation
Graphics::SetUniformEvent::SetUniformEvent () delete
Graphics::SetUniformEvent::SetUniformEvent (const Uniform & uniform) inline
Constructor for setUniformEvent.
Parameters
[in] uniform The uniform
Member Function Documentation
static std::shared_ptr<SetUniformEvent> Graphics::SetUniformEvent::create (const Uniform & uniform) inline static
Factory function for SetUniformEvent.
Parameters
[in] uniform The uniform
Returns
A newly constructed SetUniformEvent
Referenced by generated::getSetUniformEventModule(), Graphics::TileAnimator::onStart(), and Graphics::TileAnimator::onUpdate().
const Uniform Graphics::SetUniformEvent::getUniform () const inline noexcept
Gets the uniform.
Returns
The uniform.
Referenced by generated::getSetUniformEventModule().
The documentation for this class was generated from the following file:
src/graphics/set_uniform_event.h