Nymph Game Engine: Entity Class Reference
Entity Class Reference
Class for entity in the engine.
#include <entity.h>
Public Member Functions
Entity ()
Entity constructor.
void addComponent (std::shared_ptr< Component > component)
Adds a component.
void removeComponent (std::shared_ptr< Component > component)
Removes a component.
std::list< std::shared_ptr< Component > > & getComponents () noexcept
Gets the components.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets entity active or inactive.
const bool isActive () const noexcept
Determines if active.
Protected Attributes
std::list< std::shared_ptr< Component > > components
Detailed Description
Class for entity in the engine.
Constructor & Destructor Documentation
Entity::Entity ()
Entity constructor.
Member Function Documentation
void Entity::addComponent (std::shared_ptr< Component > component)
Adds a component.
Parameters
[in] component The component
References components.
Referenced by generated::getEntityModule().
std::list< std::shared_ptr< Component > > & Entity::getComponents () noexcept
Gets the components.
Returns
The components.
References components.
Referenced by generated::getEntityModule().
std::shared_ptr< Transform > Entity::getTransform () const noexcept
Gets the transform.
Returns
The transform.
Referenced by generated::getEntityModule().
const bool Entity::isActive () const noexcept
Determines if active.
Returns
True if active, False otherwise.
Referenced by generated::getEntityModule().
void Entity::removeComponent (std::shared_ptr< Component > component)
Removes a component.
Parameters
[in] component The component
References components.
Referenced by generated::getEntityModule().
void Entity::setActive (const bool active) noexcept
Sets entity active or inactive.
Parameters
[in] active True if active
Referenced by generated::getEntityModule().
Member Data Documentation
std::list<std::shared_ptr<Component> > Entity::components protected
Referenced by ComponentManager::addComponent(), addComponent(), ComponentManager::addComponents(), ComponentManager::count(), ComponentManager::destroy(), getComponents(), ComponentManager::onStart(), ComponentManager::onUpdate(), removeComponent(), ComponentManager::removeComponent(), and ComponentManager::removeComponents().
The documentation for this class was generated from the following files:
src/entity.h
src/entity.cpp