Nymph Game Engine: Graphics::UI::Skin Class Reference
Graphics::UI::Skin Class Reference
Class for UI skin.
#include <skin.h>
Public Member Functions
Skin (std::shared_ptr< BaseTexture > texture, std::shared_ptr< Shader > shader)
Skin constructor.
void setTexture (const std::shared_ptr< BaseTexture > &texture)
Sets the texture.
void setShader (const std::shared_ptr< Shader > &shader)
Sets the shader.
std::shared_ptr< BaseTexture > getTexture ()
Gets the texture.
std::shared_ptr< Shader > getShader ()
Gets the shader.
Detailed Description
Class for UI skin.
Constructor & Destructor Documentation
Graphics::UI::Skin::Skin (std::shared_ptr< BaseTexture > texture, std::shared_ptr< Shader > shader)
Skin constructor.
Parameters
[in] texture The texture
[in] shader The shader
Member Function Documentation
std::shared_ptr< Shader > Graphics::UI::Skin::getShader ()
Gets the shader.
Returns
The shader.
Referenced by generated::getSkinModule().
std::shared_ptr< BaseTexture > Graphics::UI::Skin::getTexture ()
Gets the texture.
Returns
The texture.
Referenced by generated::getSkinModule().
void Graphics::UI::Skin::setShader (const std::shared_ptr< Shader > & shader)
Sets the shader.
Parameters
[in] shader The shader
Referenced by generated::getSkinModule().
void Graphics::UI::Skin::setTexture (const std::shared_ptr< BaseTexture > & texture)
Sets the texture.
Parameters
[in] texture The texture
Referenced by generated::getSkinModule().
The documentation for this class was generated from the following files:
src/graphics/ui/skin.h
src/graphics/ui/skin.cpp