Nymph Game Engine: Graphics::UI::ChangeTextEvent Class Reference
Graphics::UI::ChangeTextEvent Class Reference
Class for change text event.
#include <change_text_event.h>
Public Member Functions
ChangeTextEvent (const std::string &text)
ChangeTextEvent constructor.
const std::string getText () const noexcept
Gets the text.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
const EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr< ChangeTextEvent > create (const std::string &text)
ChangeTextEvent factory function.
Detailed Description
Class for change text event.
Constructor & Destructor Documentation
Graphics::UI::ChangeTextEvent::ChangeTextEvent (const std::string & text) inline
ChangeTextEvent constructor.
Parameters
[in] text The text
Member Function Documentation
static std::shared_ptr<ChangeTextEvent> Graphics::UI::ChangeTextEvent::create (const std::string & text) inline static
ChangeTextEvent factory function.
Parameters
[in] text The text
Returns
A newly created ChangeTextEvent
Referenced by Utility::FPSCounter::assessCountAndGetDelta(), generated::getChangeTextEventModule(), Graphics::Camera::onStart(), and Graphics::Camera::onUpdate().
const std::string Graphics::UI::ChangeTextEvent::getText () const inline noexcept
Gets the text.
Returns
The text.
Referenced by generated::getChangeTextEventModule().
The documentation for this class was generated from the following file:
src/graphics/ui/change_text_event.h