Nymph Game Engine: Graphics::BaseTexture Class Reference
Graphics::BaseTexture Class Reference
Class for base texture.
#include <base_texture.h>
Public Member Functions
BaseTexture ()=delete
BaseTexture (const GLenum texture_type)
BaseTexture constructor.
~BaseTexture ()
Destroys the object.
const unsigned int getWidth () const noexcept
Gets the width.
const unsigned int getHeight () const noexcept
Gets the height.
virtual const bool load (const std::string &filename)
Loads the texture.
virtual void bind (const unsigned int texture_unit)
Binds texture to opengl on the texture unit.
virtual const bool isLoaded () const noexcept
Determines if loaded.
void setName (const std::string name) noexcept
Sets the name.
const std::string getName () const noexcept
Gets the name.
const std::string to_string () const noexcept
Returns a string representation of the object.
virtual const unsigned int getTextureObject () const noexcept
Gets the texture object.
Detailed Description
Class for base texture.
Constructor & Destructor Documentation
Graphics::BaseTexture::BaseTexture () delete
Graphics::BaseTexture::BaseTexture (const GLenum texture_type)
BaseTexture constructor.
Parameters
[in] texture_type The open gl texture type
Graphics::BaseTexture::~BaseTexture ()
Destroys the object.
Member Function Documentation
void Graphics::BaseTexture::bind (const unsigned int texture_unit) virtual
Binds texture to opengl on the texture unit.
Parameters
[in] texture_unit The texture unit
Referenced by generated::getBaseTextureModule().
const unsigned int Graphics::BaseTexture::getHeight () const noexcept
Gets the height.
Returns
The height.
Referenced by generated::getBaseTextureModule(), and to_string().
const std::string Graphics::BaseTexture::getName () const noexcept
Gets the name.
Returns
The name.
Referenced by generated::getBaseTextureModule(), and to_string().
const unsigned int Graphics::BaseTexture::getTextureObject () const virtual noexcept
Gets the texture object.
Returns
The texture object.
const unsigned int Graphics::BaseTexture::getWidth () const noexcept
Gets the width.
Returns
The width.
Referenced by generated::getBaseTextureModule(), and to_string().
const bool Graphics::BaseTexture::isLoaded () const virtual noexcept
Determines if loaded.
Returns
True if loaded, False otherwise.
Referenced by generated::getBaseTextureModule(), and to_string().
const bool Graphics::BaseTexture::load (const std::string & filename) virtual
Loads the texture.
Parameters
[in] filename The filename
Returns
True on success
Referenced by generated::getBaseTextureModule().
void Graphics::BaseTexture::setName (const std::string name) noexcept
Sets the name.
Parameters
[in] name The name
Referenced by generated::getBaseTextureModule().
const std::string Graphics::BaseTexture::to_string () const noexcept
Returns a string representation of the object.
Returns
String representation of the object.
References getHeight(), getName(), getWidth(), and isLoaded().
Referenced by generated::getBaseTextureModule().
The documentation for this class was generated from the following files:
src/graphics/base_texture.h
src/graphics/base_texture.cpp