Nymph Game Engine: Game::SceneGenerator Class Reference
Game::SceneGenerator Class Reference
#include <scene_generator.h>
Public Member Functions
SceneGenerator ()=delete
~SceneGenerator ()
SceneGenerator (const Map &animation_index, std::shared_ptr< Graphics::TextureManager > texture_manager, std::shared_ptr< Graphics::ShaderManager > shader_manager)
SceneGenerator constructor.
SceneGenerator (const SceneGenerator &s)=default
SceneGenerator copy constructor.
SceneGenerator & operator= (const SceneGenerator &other)=default
SceneGenerator equal operator.
std::shared_ptr< Scene > createSceneFromMap (const unsigned int patch_width_tiles, const unsigned int patch_height_tiles, const Map &map)
Creates a scene from a map.
std::shared_ptr< Entity > getDynamicEntityByName (const std::string &name)
Gets a dynamic entity by name.
std::vector< std::string > getDynamicEntityNames () const noexcept
Gets all dynamic entity names.
const std::string getStrippedMapName (const std::string path)
Strips path specification from map name.
Constructor & Destructor Documentation
Game::SceneGenerator::SceneGenerator () delete
Game::SceneGenerator::~SceneGenerator ()
Game::SceneGenerator::SceneGenerator (const Map & animation_index, std::shared_ptr< Graphics::TextureManager > texture_manager, std::shared_ptr< Graphics::ShaderManager > shader_manager)
SceneGenerator constructor.
Parameters
[in] animation_index The animation index containing all animations
[in] texture_manager The texture manager
[in] shader_manager The shader manager
Game::SceneGenerator::SceneGenerator (const SceneGenerator & s) default
SceneGenerator copy constructor.
Parameters
[in] s The other SceneGenerator
Member Function Documentation
std::shared_ptr< Scene > Game::SceneGenerator::createSceneFromMap (const unsigned int patch_width_tiles, const unsigned int patch_height_tiles, const Map & map)
Creates a scene from a map.
Parameters
[in] patch_width_tiles The patch width in tiles
[in] patch_height_tiles The patch height in tiles
[in] map The map
Returns
A newly created scene
References Game::Map::getImpl().
Referenced by generated::getSceneGeneratorModule().
std::shared_ptr< Entity > Game::SceneGenerator::getDynamicEntityByName (const std::string & name)
Gets a dynamic entity by name.
Parameters
[in] name The name
Returns
The dynamic entity by name.
Referenced by generated::getSceneGeneratorModule().
std::vector< std::string > Game::SceneGenerator::getDynamicEntityNames () const noexcept
Gets all dynamic entity names.
Returns
The dynamic entity names.
Referenced by generated::getSceneGeneratorModule().
const std::string Game::SceneGenerator::getStrippedMapName (const std::string path)
Strips path specification from map name.
Parameters
[in] path The path
Returns
The stripped map name.
Referenced by generated::getSceneGeneratorModule().
SceneGenerator& Game::SceneGenerator::operator= (const SceneGenerator & other) default
SceneGenerator equal operator.
Parameters
[in] other The other SceneGenerator
Returns
*this
The documentation for this class was generated from the following files:
src/game/scene_generator.h
src/game/scene_generator.cpp