Nymph Game Engine: Graphics::Renderable Class Reference
Graphics::Renderable Class Reference
Class for renderable.
#include <renderable.h>
Public Member Functions
Renderable (const unsigned int vertex_array_object, const VertexData &vertex_data)
Renderable constructor.
Renderable (const Renderable &)=delete
Renderable operator= (Renderable &)=delete
Renderable (Renderable &&renderable)
Renderable & operator= (Renderable &&renderable)
virtual ~Renderable ()
void setShader (std::shared_ptr< Shader > shader_object) noexcept
Sets the shader.
const std::shared_ptr< Shader > getShader () const noexcept
Gets the shader.
void addTexture (const unsigned int unit, const std::string uniform_name, std::shared_ptr< BaseTexture > texture_object) noexcept
Adds a texture.
void removeTexture (const unsigned int unit)
Removes a texture.
const std::map< unsigned int, std::shared_ptr< BaseTexture > > getTextures () const noexcept
Gets the textures.
void setLightReactive (const bool reactive) noexcept
Sets if the renderable should be light reactive.
const bool isLightReactive () const noexcept
Determines if light reactive.
void setAmbientLight (const glm::vec3 color) noexcept
Sets the ambient light.
const glm::vec3 getAmbientLight () const noexcept
Gets the ambient light.
void setAmbientIntensity (const float intensity) noexcept
Sets the ambient intensity.
const float getAmbientIntensity () const noexcept
Gets the ambient intensity.
void addInfluencingLight (std::shared_ptr< Light > light) noexcept
Adds an influencing light.
void clearInfluencingLights ()
Clears all influencing lights.
const std::string to_string () const noexcept
Returns a string representation of the object.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
const float highestZ () const noexcept
The highest possible z value in the renderable.
const unsigned int getVertexArrayBinding () const noexcept
Gets the vertex array binding.
const VertexData getVertexData () const noexcept
Gets the vertex data.
virtual void onDestroy () override
Called when the engine is shutting down.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const override
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Static Public Member Functions
static std::shared_ptr< Renderable > create (const VertexData &vertex_data)
Renderable factory function.
Protected Member Functions
void setUniform (const Uniform &uniform) noexcept
Renderable ()
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes
std::set< Uniform > uniforms
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Additional Inherited Members
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for renderable.
Constructor & Destructor Documentation
Graphics::Renderable::Renderable () inline protected
Graphics::Renderable::Renderable (const unsigned int vertex_array_object, const VertexData & vertex_data)
Renderable constructor.
Parameters
[in] vertex_array_object The vertex array object
[in] vertex_data The vertex data
Graphics::Renderable::Renderable (const Renderable &) delete
Graphics::Renderable::Renderable (Renderable && renderable)
Graphics::Renderable::~Renderable () virtual
References onDestroy().
Member Function Documentation
void Graphics::Renderable::addInfluencingLight (std::shared_ptr< Light > light) noexcept
Adds an influencing light.
Parameters
[in] light The light
Referenced by generated::getRenderableModule().
void Graphics::Renderable::addTexture (const unsigned int unit, const std::string uniform_name, std::shared_ptr< BaseTexture > texture_object) noexcept
Adds a texture.
Parameters
[in] unit The unit
[in] uniform_name The uniform name
[in] texture_object The texture object
References Graphics::Uniform::setData().
Referenced by Graphics::UI::Element::Element(), and generated::getRenderableModule().
const std::string Graphics::Renderable::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, Graphics::UI::Area, and Graphics::UI::QuitButton.
Referenced by generated::getRenderableModule().
void Graphics::Renderable::clearInfluencingLights ()
Clears all influencing lights.
Referenced by generated::getRenderableModule().
std::shared_ptr< Renderable > Graphics::Renderable::create (const VertexData & vertex_data) static
Renderable factory function.
Parameters
[in] vertex_data The vertex data
Returns
newly created Renderable
References Graphics::VertexData::generateVertexArrayObject().
const float Graphics::Renderable::getAmbientIntensity () const noexcept
Gets the ambient intensity.
Returns
The ambient intensity.
Referenced by generated::getRenderableModule().
const glm::vec3 Graphics::Renderable::getAmbientLight () const noexcept
Gets the ambient light.
Returns
The ambient light.
Referenced by generated::getRenderableModule().
const std::shared_ptr< Shader > Graphics::Renderable::getShader () const noexcept
Gets the shader.
Returns
The shader.
Referenced by generated::getRenderableModule().
const std::map< unsigned int, std::shared_ptr< BaseTexture > > Graphics::Renderable::getTextures () const noexcept
Gets the textures.
Returns
A map of texture units to textures
Referenced by generated::getRenderableModule().
const unsigned long long Graphics::Renderable::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
References Component::getTransform().
const unsigned int Graphics::Renderable::getVertexArrayBinding () const noexcept
Gets the vertex array binding.
Returns
The vertex array binding.
const VertexData Graphics::Renderable::getVertexData () const noexcept
Gets the vertex data.
Returns
The vertex data.
void Graphics::Renderable::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
References Events::ADD_TEXTURE, Component::handleQueuedEvent(), Events::REMOVE_TEXTURE, Events::SET_SHADER, Events::SET_UNIFORM, and setUniform().
Referenced by Graphics::UI::Element::handleQueuedEvent(), and onNotifyNow().
const float Graphics::Renderable::highestZ () const noexcept
The highest possible z value in the renderable.
Returns
A float representing the highest z value in the renderable
References Graphics::VertexData::highestZ().
Referenced by to_string().
const bool Graphics::Renderable::isLightReactive () const noexcept
Determines if light reactive.
Returns
True if light reactive, False otherwise.
Referenced by generated::getRenderableModule().
void Graphics::Renderable::log (el::base::type::ostream_t & os) const override virtual
Reimplemented from Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
References to_string().
void Graphics::Renderable::onDestroy () override virtual
Called when the engine is shutting down.
Implements Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
Referenced by ~Renderable().
void Graphics::Renderable::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
References handleQueuedEvent().
void Graphics::Renderable::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
References Graphics::Uniform::setData(), and setUniform().
const bool Graphics::Renderable::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
Reimplemented in Graphics::UI::Element, Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
References Graphics::VertexData::getIndexCount(), Component::getTransform(), Graphics::VertexData::getVertexCount(), Component::isActive(), Graphics::Uniform::setData(), and setUniform().
Referenced by Graphics::UI::Element::onUpdate().
Renderable Graphics::Renderable::operator= (Renderable &) delete
Renderable & Graphics::Renderable::operator= (Renderable && renderable)
void Graphics::Renderable::removeTexture (const unsigned int unit)
Removes a texture.
Parameters
[in] unit The unit
Referenced by generated::getRenderableModule().
void Graphics::Renderable::setAmbientIntensity (const float intensity) noexcept
Sets the ambient intensity.
Parameters
[in] intensity The intensity
Referenced by generated::getRenderableModule().
void Graphics::Renderable::setAmbientLight (const glm::vec3 color) noexcept
Sets the ambient light.
Parameters
[in] color The color
Referenced by generated::getRenderableModule().
void Graphics::Renderable::setLightReactive (const bool reactive) noexcept
Sets if the renderable should be light reactive.
Parameters
[in] reactive True if reactive
Referenced by generated::getRenderableModule().
void Graphics::Renderable::setShader (std::shared_ptr< Shader > shader_object) noexcept
Sets the shader.
Parameters
[in] shader_object The shader object
Referenced by Graphics::UI::Element::Element(), and generated::getRenderableModule().
void Graphics::Renderable::setUniform (const Uniform & uniform) protected noexcept
Referenced by handleQueuedEvent(), onStart(), onUpdate(), and Graphics::UI::Element::setAnchorPoint().
const std::string Graphics::Renderable::to_string () const noexcept
Returns a string representation of the object.
Returns
String representation of the object.
References highestZ(), and Component::to_string().
Referenced by generated::getRenderableModule(), log(), and Graphics::UI::Element::to_string().
Member Data Documentation
std::set<Uniform> Graphics::Renderable::uniforms protected
The documentation for this class was generated from the following files:
src/graphics/renderable.h
src/graphics/renderable.cpp