Nymph Game Engine: Utility::FPSCounter Class Reference
Utility::FPSCounter Class Reference
Class for fps counter.
#include <fps_counter.h>
Public Member Functions
FPSCounter (const float max_fps)
FPSCounter cunstructer.
virtual ~FPSCounter ()=default
Destroys the object.
const float assessCountAndGetDelta ()
Calculates frame delta from FPS counter.
const float getMaxFPS () const noexcept
Gets the maximum fps.
const float getCurrentFPS () const noexcept
Gets the current fps.
const float getAverageFPS () const noexcept
Gets the average fps.
void resetAverageFPS () noexcept
Resets FPS Average.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Detailed Description
Class for fps counter.
Constructor & Destructor Documentation
Utility::FPSCounter::FPSCounter (const float max_fps = 0.0f)
FPSCounter cunstructer.
Parameters
[in] max_fps The maximum fps
virtual Utility::FPSCounter::~FPSCounter () virtual default
Destroys the object.
Member Function Documentation
const float Utility::FPSCounter::assessCountAndGetDelta ()
Calculates frame delta from FPS counter.
Returns
frame delta
References Graphics::UI::ChangeTextEvent::create(), and Events::Subject::notifyNow().
const float Utility::FPSCounter::getAverageFPS () const noexcept
Gets the average fps.
Returns
The average fps.
Referenced by generated::getFPSCounterModule().
const float Utility::FPSCounter::getCurrentFPS () const noexcept
Gets the current fps.
Returns
The current fps.
Referenced by generated::getFPSCounterModule().
const float Utility::FPSCounter::getMaxFPS () const noexcept
Gets the maximum fps.
Returns
The maximum fps.
Referenced by generated::getFPSCounterModule().
void Utility::FPSCounter::resetAverageFPS () noexcept
Resets FPS Average.
Referenced by generated::getFPSCounterModule().
The documentation for this class was generated from the following files:
src/utility/fps_counter.h
src/utility/fps_counter.cpp