Nymph Game Engine: Input::KeyRepeatEvent Class Reference
Input::KeyRepeatEvent Class Reference
Class for key repeat event.
#include <key_repeat_event.h>
Public Member Functions
KeyRepeatEvent (const int key)
Constructor for KeyRepeatEvent.
const int getKey () const noexcept
Gets the key.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
const EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr< KeyRepeatEvent > create (const int key)
Factory function.
Detailed Description
Class for key repeat event.
Constructor & Destructor Documentation
Input::KeyRepeatEvent::KeyRepeatEvent (const int key) inline
Constructor for KeyRepeatEvent.
Parameters
[in] key The key
Member Function Documentation
static std::shared_ptr<KeyRepeatEvent> Input::KeyRepeatEvent::create (const int key) inline static
Factory function.
Parameters
[in] key The key
Returns
Newly constructed KeyRepeatEvent
Referenced by generated::getKeyRepeatEventModule(), and Input::InputSystem::pollForInput().
const int Input::KeyRepeatEvent::getKey () const inline noexcept
Gets the key.
Returns
The key.
Referenced by generated::getKeyRepeatEventModule().
The documentation for this class was generated from the following file:
src/input/key_repeat_event.h