#ifndef EVENTS_H
#define EVENTS_H

#include "../graphics/ui/change_text_event.h"
#include "../graphics/ui/resume_key_input_event.h"
#include "../graphics/ui/suspend_key_input_event.h"
#include "../graphics/set_uniform_event.h"
#include "../input/character_typed_event.h"
#include "../input/cursor_enter_event.h"
#include "../input/cursor_leave_event.h"
#include "../input/key_down_event.h"
#include "../input/key_up_event.h"
#include "../input/key_repeat_event.h"
#include "../input/mouse_button_down_event.h"
#include "../input/mouse_button_up_event.h"
#include "../input/mouse_cursor_event.h"
#include "../input/mouse_scroll_event.h"
#include "../utility/debug_command_event.h"
#include "../utility/list_characters_event.h"
#include "../utility/list_layers_event.h"
#include "../utility/list_maps_event.h"
#include "../utility/load_character_event.h"
#include "../utility/load_map_event.h"
#include "../utility/toggle_free_camera_event.h"
#include "../utility/toggle_layer_event.h"
#include "../utility/toggle_lights_event.h"
#include "../utility/window_exit_event.h"
#include "../game/animation_trigger_event.hpp"
#include "../game/sprite_move_event.h"
#include "../set_active_event.h"
#include "../set_entity_active_event.h"

#endif
