Nymph Game Engine: Utility::ConfigManager Class Reference
Utility::ConfigManager Class Reference
Class for configuration manager to load json configurations.
#include <config_manager.h>
Public Member Functions
ConfigManager ()
Constructs the configManager.
const bool loadConfig (const std::string &file_path)
Loads a configuration.
const int getInt (const std::string &key)
Gets an int from config.
const unsigned int getUnsignedInt (const std::string &key)
Gets an unsigned int from config.
const std::string getString (const std::string &key)
Gets a string from config.
const float getFloat (const std::string &key)
Gets a float from config.
const double getDouble (const std::string &key)
Gets a double from config.
const bool getBool (const std::string &key)
Gets a bool from config.
const std::vector< std::string > getStringVector (const std::string &key)
Gets a string vector from config.
const std::vector< unsigned int > getUnsignedIntVector (const std::string &key)
Gets an unsigned int vector from config.
Detailed Description
Class for configuration manager to load json configurations.
Constructor & Destructor Documentation
Utility::ConfigManager::ConfigManager ()
Constructs the configManager.
Member Function Documentation
const bool Utility::ConfigManager::getBool (const std::string & key)
Gets a bool from config.
Parameters
[in] key The key
Returns
The bool.
Referenced by generated::getConfigManagerModule(), and Engine::setup().
const double Utility::ConfigManager::getDouble (const std::string & key)
Gets a double from config.
Parameters
[in] key The key
Returns
The double.
Referenced by generated::getConfigManagerModule().
const float Utility::ConfigManager::getFloat (const std::string & key)
Gets a float from config.
Parameters
[in] key The key
Returns
The float.
Referenced by generated::getConfigManagerModule(), and Engine::setup().
const int Utility::ConfigManager::getInt (const std::string & key)
Gets an int from config.
Parameters
[in] key The key
Returns
The int.
Referenced by generated::getConfigManagerModule(), and Engine::setup().
const std::string Utility::ConfigManager::getString (const std::string & key)
Gets a string from config.
Parameters
[in] key The key
Returns
The string.
Referenced by generated::getConfigManagerModule(), and Engine::setup().
const std::vector< std::string > Utility::ConfigManager::getStringVector (const std::string & key)
Gets a string vector from config.
Parameters
[in] key The key
Returns
The string vector.
Referenced by generated::getConfigManagerModule().
const unsigned int Utility::ConfigManager::getUnsignedInt (const std::string & key)
Gets an unsigned int from config.
Parameters
[in] key The key
Returns
The unsigned int.
Referenced by generated::getConfigManagerModule().
const std::vector< unsigned int > Utility::ConfigManager::getUnsignedIntVector (const std::string & key)
Gets an unsigned int vector from config.
Parameters
[in] key The key
Returns
The unsigned int vector.
Referenced by generated::getConfigManagerModule().
const bool Utility::ConfigManager::loadConfig (const std::string & file_path)
Loads a configuration.
Parameters
[in] file_path The file path
Returns
True if successful
The documentation for this class was generated from the following files:
src/utility/config_manager.h
src/utility/config_manager.cpp