Nymph Game Engine: Graphics::TileAnimator Class Reference
Graphics::TileAnimator Class Reference
Class for tile animator.
#include <tile_animator.h>
Public Member Functions
TileAnimator ()=delete
TileAnimator (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width_pixels, const unsigned int tile_height_pixels)
TileAnimator Constructor.
void setStartingState (const std::string &state)
Sets the starting state.
void addFrameFront (const std::string &state, const glm::ivec2 &frame_pos, const unsigned int frame_time, bool set_current=false)
Adds a frame to the front.
void addFrameBack (const std::string &state, const glm::ivec2 &frame_pos, const unsigned int frame_time, bool set_current=false)
Adds a frame to the back.
void popFrameFront (const std::string &state)
Pops a frame from the front.
void popFrameBack (const std::string &state)
Pops a frame from the back.
void triggerAnimation (const std::string &state)
Triggers animation of state.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
virtual void onDestroy () override
Called when the engine is shutting down.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Static Public Member Functions
static std::shared_ptr< TileAnimator > create (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width=32, const unsigned int tile_height=32)
Factory function for TileAnimator.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for tile animator.
Constructor & Destructor Documentation
Graphics::TileAnimator::TileAnimator () delete
Graphics::TileAnimator::TileAnimator (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width_pixels, const unsigned int tile_height_pixels)
TileAnimator Constructor.
Parameters
[in] tileset_width The tileset width
[in] tileset_height The tileset height
[in] tile_width_pixels The tile width pixels
[in] tile_height_pixels The tile height pixels
Member Function Documentation
void Graphics::TileAnimator::addFrameBack (const std::string & state, const glm::ivec2 & frame_pos, const unsigned int frame_time, bool set_current = false)
Adds a frame to the back.
Parameters
[in] state The state
[in] frame_pos The frame position
[in] frame_time The frame time
[in] set_current The set current
Referenced by generated::getTileAnimatorModule().
void Graphics::TileAnimator::addFrameFront (const std::string & state, const glm::ivec2 & frame_pos, const unsigned int frame_time, bool set_current = false)
Adds a frame to the front.
Parameters
[in] state The state
[in] frame_pos The frame position
[in] frame_time The frame time
[in] set_current The set current
Referenced by generated::getTileAnimatorModule().
const std::string Graphics::TileAnimator::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Referenced by generated::getTileAnimatorModule().
std::shared_ptr< TileAnimator > Graphics::TileAnimator::create (const unsigned int tileset_width, const unsigned int tileset_height, const unsigned int tile_width = 32, const unsigned int tile_height = 32) static
Factory function for TileAnimator.
Parameters
[in] tileset_width The tileset width
[in] tileset_height The tileset height
[in] tile_width The tile width
[in] tile_height The tile height
Returns
Newly created TileAnimator
Referenced by generated::getTileAnimatorModule().
const unsigned long long Graphics::TileAnimator::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
References Component::getId().
void Graphics::TileAnimator::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
References Events::ANIMATION_TRIGGER, Component::handleQueuedEvent(), and triggerAnimation().
Referenced by onNotifyNow(), and onUpdate().
void Graphics::TileAnimator::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Component.
References Component::log().
void Graphics::TileAnimator::onDestroy () override virtual
Called when the engine is shutting down.
Implements Component.
void Graphics::TileAnimator::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
References handleQueuedEvent().
void Graphics::TileAnimator::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
References Graphics::SetUniformEvent::create(), Events::Subject::notify(), and Graphics::Uniform::setData().
const bool Graphics::TileAnimator::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
References Component::active, Graphics::SetUniformEvent::create(), Events::Observer::eventsWaiting(), Events::Observer::getEvent(), handleQueuedEvent(), Events::Subject::notifyNow(), and Graphics::Uniform::setData().
void Graphics::TileAnimator::popFrameBack (const std::string & state)
Pops a frame from the back.
Parameters
[in] state The state
Referenced by generated::getTileAnimatorModule().
void Graphics::TileAnimator::popFrameFront (const std::string & state)
Pops a frame from the front.
Parameters
[in] state The state
Referenced by generated::getTileAnimatorModule().
void Graphics::TileAnimator::setStartingState (const std::string & state)
Sets the starting state.
Parameters
[in] state The state
Referenced by generated::getTileAnimatorModule().
void Graphics::TileAnimator::triggerAnimation (const std::string & state)
Triggers animation of state.
Parameters
[in] state The state
Referenced by generated::getTileAnimatorModule(), and handleQueuedEvent().
The documentation for this class was generated from the following files:
src/graphics/tile_animator.h
src/graphics/tile_animator.cpp