Nymph Game Engine: Game::SpriteMovement Class Reference
Game::SpriteMovement Class Reference
Class for sprite movement.
#include <sprite_movement.h>
Public Member Functions
const bool onUpdate (const double delta) override
Called every engine loop.
void onStart () override
Called when the engine starts and when a new scene is loaded.
void onDestroy () override
Called when the engine is shutting down.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
SpriteMovement ()
Sprite Movement constructor.
void setAnimationStringState (const SpriteState &state, const std::string &str)
Sets the animation string state.
void setMovingSpeed (const float speed)
Sets the moving speed.
void setMoveQuantization (const float number_of_tiles)
Sets the move quantization.
void stopMovingLeft ()
Stops the sprite moving left.
void moveLeft ()
Starts the sprite moving left.
void stopMovingRight ()
Stops the sprite moving right.
void moveRight ()
Starts the sprite moving right.
void stopMovingUp ()
Stops the sprite moving up.
void moveUp ()
Starts the sprite moving up.
void stopMovingDown ()
Stops the sprite moving down.
void moveDown ()
Starts the sprite moving down.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void log (el::base::type::ostream_t &os) const override
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for sprite movement.
Constructor & Destructor Documentation
Game::SpriteMovement::SpriteMovement ()
Sprite Movement constructor.
Member Function Documentation
const std::string Game::SpriteMovement::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Referenced by generated::getSpriteMovementModule().
const unsigned long long Game::SpriteMovement::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
References Component::getId().
void Game::SpriteMovement::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
References Component::handleQueuedEvent(), Events::KEY_DOWN, Events::KEY_UP, moveDown(), moveLeft(), moveRight(), moveUp(), stopMovingDown(), stopMovingLeft(), stopMovingRight(), and stopMovingUp().
Referenced by onNotifyNow(), and onUpdate().
void Game::SpriteMovement::log (el::base::type::ostream_t & os) const override virtual
Reimplemented from Component.
References Component::log().
void Game::SpriteMovement::moveDown ()
Starts the sprite moving down.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::moveLeft ()
Starts the sprite moving left.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::moveRight ()
Starts the sprite moving right.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::moveUp ()
Starts the sprite moving up.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::onDestroy () inline override virtual
Called when the engine is shutting down.
Implements Component.
void Game::SpriteMovement::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
References handleQueuedEvent().
void Game::SpriteMovement::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
const bool Game::SpriteMovement::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
References Component::active, Game::AnimationTriggerEvent::create(), Game::SpriteMoveEvent::create(), Events::Observer::eventsWaiting(), Game::FACE_DOWN, Game::FACE_LEFT, Game::FACE_RIGHT, Game::FACE_UP, Events::Observer::getEvent(), Component::getTransform(), handleQueuedEvent(), Game::MOVE_DOWN, Game::MOVE_LEFT, Game::MOVE_RIGHT, Game::MOVE_UP, Events::Subject::notify(), and Events::Subject::notifyNow().
void Game::SpriteMovement::setAnimationStringState (const SpriteState & state, const std::string & str)
Sets the animation string state.
Parameters
[in] state The state
[in] str The string
Referenced by generated::getSpriteMovementModule().
void Game::SpriteMovement::setMoveQuantization (const float number_of_tiles)
Sets the move quantization.
Parameters
[in] number_of_tiles The number of tiles
Referenced by generated::getSpriteMovementModule().
void Game::SpriteMovement::setMovingSpeed (const float speed)
Sets the moving speed.
Parameters
[in] speed The speed
Referenced by generated::getSpriteMovementModule().
void Game::SpriteMovement::stopMovingDown ()
Stops the sprite moving down.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::stopMovingLeft ()
Stops the sprite moving left.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::stopMovingRight ()
Stops the sprite moving right.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
void Game::SpriteMovement::stopMovingUp ()
Stops the sprite moving up.
Referenced by generated::getSpriteMovementModule(), and handleQueuedEvent().
The documentation for this class was generated from the following files:
src/game/sprite_movement.h
src/game/sprite_movement.cpp