Nymph Game Engine: Engine Class Reference
Engine Class Reference
Class for engine.
#include <engine.h>
Public Member Functions
Engine ()
Engine constructor.
virtual ~Engine ()=default
Engine destructor.
void addScene (std::shared_ptr< Game::Scene > scene) noexcept
Adds a scene to the engine.
std::shared_ptr< Game::Scene > findSceneByName (const std::string &name) noexcept
Finds a scene by name.
std::map< std::shared_ptr< Game::Scene >, bool > getScenes () const noexcept
Gets the scenes.
void activateScene (const std::string &name)
Activates a scene by name.
void deactivateScene (const std::string &name)
Deactivates a scene by name.
const std::vector< std::string > getSceneNames () const noexcept
Gets the scene names.
const std::vector< std::string > getActiveSceneNames () const noexcept
Gets the active scene names.
void timeToExit () noexcept
This is to signal the engine that it is time to shut down.
void setup (const std::string config_path)
Sets up the engine.
void mainLoop ()
Triggers the main loop for the engine.
void cleanUp ()
Cleans up before exiting.
Detailed Description
Class for engine.
Constructor & Destructor Documentation
Engine::Engine ()
Engine constructor.
virtual Engine::~Engine () virtual default
Engine destructor.
Member Function Documentation
void Engine::activateScene (const std::string & name)
Activates a scene by name.
Parameters
[in] name The name
References findSceneByName().
Referenced by generated::getEngineModule().
void Engine::addScene (std::shared_ptr< Game::Scene > scene) noexcept
Adds a scene to the engine.
Parameters
[in] scene The scene
Referenced by generated::getEngineModule().
void Engine::cleanUp ()
Cleans up before exiting.
void Engine::deactivateScene (const std::string & name)
Deactivates a scene by name.
Parameters
[in] name The name
References findSceneByName().
Referenced by generated::getEngineModule().
std::shared_ptr< Game::Scene > Engine::findSceneByName (const std::string & name) noexcept
Finds a scene by name.
Parameters
[in] name The name
Returns
The scene, nullptr if it doesn't exist
Referenced by activateScene(), deactivateScene(), and generated::getEngineModule().
const std::vector< std::string > Engine::getActiveSceneNames () const noexcept
Gets the active scene names.
Returns
The active scene names.
Referenced by generated::getEngineModule().
const std::vector< std::string > Engine::getSceneNames () const noexcept
Gets the scene names.
Returns
The scene names.
Referenced by generated::getEngineModule().
std::map< std::shared_ptr< Game::Scene >, bool > Engine::getScenes () const noexcept
Gets the scenes.
Returns
The scenes.
Referenced by generated::getEngineModule().
void Engine::mainLoop ()
Triggers the main loop for the engine.
void Engine::setup (const std::string config_path)
Sets up the engine.
Parameters
[in] config_path The configuration path
References ComponentManager::addComponent(), Utility::ConfigManager::getBool(), Utility::ConfigManager::getFloat(), Utility::ConfigManager::getInt(), Graphics::Camera::getProjectionMatrix(), Utility::ConfigManager::getString(), Component::getTransform(), and Graphics::GraphicsSystem::getWindow().
void Engine::timeToExit () noexcept
This is to signal the engine that it is time to shut down.
Referenced by generated::getEngineModule().
The documentation for this class was generated from the following files:
src/engine.h
src/engine.cpp