Nymph Game Engine: Graphics::TextureManager Class Reference
Graphics::TextureManager Class Reference
Class for texture manager.
#include <texture_manager.h>
Public Member Functions
TextureManager ()
TextureManager constructor.
~TextureManager ()
Destroys the object.
const bool loadTexture (const std::string &path)
Loads a texture.
std::shared_ptr< BaseTexture > operator[] (const std::string &name) const
Get's texture with name.
std::shared_ptr< BaseTexture > getTexture (const std::string &name) const
Gets the texture.
const bool textureExists (const std::string &name) const noexcept
Function to see if texture with name exists.
Static Public Member Functions
static const std::string getNameFromPath (const std::string &path) noexcept
Gets the name from path.
Detailed Description
Class for texture manager.
Constructor & Destructor Documentation
Graphics::TextureManager::TextureManager ()
TextureManager constructor.
Graphics::TextureManager::~TextureManager ()
Destroys the object.
Member Function Documentation
const std::string Graphics::TextureManager::getNameFromPath (const std::string & path) static noexcept
Gets the name from path.
Parameters
[in] path The path
Returns
The name from path.
Referenced by loadTexture().
std::shared_ptr< BaseTexture > Graphics::TextureManager::getTexture (const std::string & name) const
Gets the texture.
Parameters
[in] name The name
Returns
The texture.
Referenced by generated::getTextureManagerModule(), and operator[]().
const bool Graphics::TextureManager::loadTexture (const std::string & path)
Loads a texture.
Parameters
[in] path The path
Returns
True if successful
References getNameFromPath().
Referenced by generated::getTextureManagerModule().
std::shared_ptr< BaseTexture > Graphics::TextureManager::operator[] (const std::string & name) const
Get's texture with name.
Parameters
[in] name The name
Returns
A texture
References getTexture().
const bool Graphics::TextureManager::textureExists (const std::string & name) const noexcept
Function to see if texture with name exists.
Parameters
[in] name The name
Returns
True if it exists
Referenced by generated::getTextureManagerModule().
The documentation for this class was generated from the following files:
src/graphics/texture_manager.h
src/graphics/texture_manager.cpp