Nymph Game Engine: Graphics::Light Class Reference
Graphics::Light Class Reference
Class for light.
#include <light.h>
Public Types
enum Type : unsigned int { POINT, SPOT }
Light type enum.
Public Member Functions
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
virtual void onDestroy () override
Called when the engine is shutting down.
Light (const Light::Type &type=Type::POINT)
Light constructor.
~Light ()
Destroys the object.
void setColor (const glm::vec3 color) noexcept
Sets the color.
const glm::vec3 getColor () const noexcept
Gets the color.
void setIntensity (const float intensity) noexcept
Sets the intensity.
const float getIntensity () const noexcept
Gets the intensity.
void setLinearAttenuation (const float linear) noexcept
Sets the linear attenuation.
const float getLinearAttenuation () const noexcept
Gets the linear attenuation.
void setQuadraticAttenuation (const float quadratic) noexcept
Sets the quadratic attenuation.
const float getQuadraticAttenuation () const noexcept
Gets the quadratic attenuation.
const bool castsQuantizedBands () const noexcept
Function to see if lights cast quantized bands or are smooth.
void setNumberOfQuantizedBands (const int bands) noexcept
Sets the number of quantized bands.
const int getNumberOfQuantizedBands () const noexcept
Gets the number of quantized bands.
void setConeAngle (const float angle) noexcept
Sets the cone angle.
const float getConeAngle () const noexcept
Gets the cone angle.
void setConeDirection (const glm::vec3 direction) noexcept
Sets the cone direction.
const glm::vec3 getConeDirection () const noexcept
Gets the cone direction.
const Light::Type getType () const noexcept
Gets the type.
const float influenceOnComponent (const Component &component) const
Calculates a light's influence on a given component.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Static Public Member Functions
static const Light::Type stringToType (const std::string &str)
static const std::string typeToString (const Light::Type &type)
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for light.
Member Enumeration Documentation
enum Graphics::Light::Type : unsigned int
Light type enum.
Enumerator
POINT
SPOT
Constructor & Destructor Documentation
Graphics::Light::Light (const Light::Type & type = Type::POINT)
Light constructor.
Parameters
[in] type The type
Graphics::Light::~Light ()
Destroys the object.
Member Function Documentation
const bool Graphics::Light::castsQuantizedBands () const noexcept
Function to see if lights cast quantized bands or are smooth.
Returns
True if lights cast quantized bands
Referenced by generated::getLightModule().
const std::string Graphics::Light::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Referenced by generated::getLightModule().
const glm::vec3 Graphics::Light::getColor () const noexcept
Gets the color.
Returns
The color.
Referenced by generated::getLightModule().
const float Graphics::Light::getConeAngle () const noexcept
Gets the cone angle.
Returns
The cone angle.
Referenced by generated::getLightModule().
const glm::vec3 Graphics::Light::getConeDirection () const noexcept
Gets the cone direction.
Returns
The cone direction.
Referenced by generated::getLightModule().
const float Graphics::Light::getIntensity () const noexcept
Gets the intensity.
Returns
The intensity.
Referenced by generated::getLightModule().
const float Graphics::Light::getLinearAttenuation () const noexcept
Gets the linear attenuation.
Returns
The linear attenuation.
Referenced by generated::getLightModule().
const int Graphics::Light::getNumberOfQuantizedBands () const noexcept
Gets the number of quantized bands.
Returns
The number of quantized bands.
Referenced by generated::getLightModule().
const float Graphics::Light::getQuadraticAttenuation () const noexcept
Gets the quadratic attenuation.
Returns
The quadratic attenuation.
Referenced by generated::getLightModule().
const Light::Type Graphics::Light::getType () const noexcept
Gets the type.
Returns
The type.
Referenced by generated::getLightModule().
const unsigned long long Graphics::Light::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
References Component::getId().
const float Graphics::Light::influenceOnComponent (const Component & component) const
Calculates a light's influence on a given component.
Parameters
[in] component The component
Returns
Influence amount clamped 0.0, 1.0, on the given component
References Component::getTransform().
Referenced by generated::getLightModule().
void Graphics::Light::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Component.
References Component::getTransform(), and typeToString().
void Graphics::Light::onDestroy () override virtual
Called when the engine is shutting down.
Implements Component.
void Graphics::Light::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
const bool Graphics::Light::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
void Graphics::Light::setColor (const glm::vec3 color) noexcept
Sets the color.
Parameters
[in] color The color
Referenced by generated::getLightModule().
void Graphics::Light::setConeAngle (const float angle) noexcept
Sets the cone angle.
Parameters
[in] angle The angle
Referenced by generated::getLightModule().
void Graphics::Light::setConeDirection (const glm::vec3 direction) noexcept
Sets the cone direction.
Parameters
[in] direction The direction
Referenced by generated::getLightModule().
void Graphics::Light::setIntensity (const float intensity) noexcept
Sets the intensity.
Parameters
[in] intensity The intensity
Referenced by generated::getLightModule().
void Graphics::Light::setLinearAttenuation (const float linear) noexcept
Sets the linear attenuation.
Parameters
[in] linear The linear
Referenced by generated::getLightModule().
void Graphics::Light::setNumberOfQuantizedBands (const int bands) noexcept
Sets the number of quantized bands.
Parameters
[in] bands The bands
Referenced by generated::getLightModule().
void Graphics::Light::setQuadraticAttenuation (const float quadratic) noexcept
Sets the quadratic attenuation.
Parameters
[in] quadratic The quadratic
Referenced by generated::getLightModule().
static const Light::Type Graphics::Light::stringToType (const std::string & str) inline static
static const std::string Graphics::Light::typeToString (const Light::Type & type) inline static
Referenced by log().
The documentation for this class was generated from the following files:
src/graphics/light.h
src/graphics/light.cpp