Nymph Game Engine: Graphics::Camera Class Reference
Graphics::Camera Class Reference
Class for camera.
#include <camera.h>
Public Member Functions
Camera ()=delete
Camera (const std::shared_ptr< ShaderManager > shader_manager)
Constructor for Camera.
Camera (const std::shared_ptr< ShaderManager > shader_manager, const float viewport_width, const float viewport_height, const float near=0.1, const float far=1.0)
Constructor for Camera.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
virtual void onDestroy () override
Called when the engine is shutting down.
void setScreenPaddingInTiles (const int padding) noexcept
Sets the screen padding in tiles.
const int getScreenPaddingInTiles () const noexcept
Gets the screen padding in tiles.
void setWidth (const float width) noexcept
Sets the width.
const float getWidth () const noexcept
Gets the width.
void setHeight (const float height) noexcept
Sets the height.
const float getHeight () const noexcept
Gets the height.
void setNear (const float near) noexcept
Sets the near z plane.
const float getNear () const noexcept
Gets the near z plane.
void setFar (const float far) noexcept
Sets the far z plane.
const float getFar () const noexcept
Gets the far z plane.
void setFreeCameraSpeed (const float speed) noexcept
Sets the free camera speed when in free camera mode.
const float getFreeCameraSpeed () const noexcept
Gets the free camera speed when in free camera mode.
const glm::mat4 getProjectionMatrix () const noexcept
Gets the projection matrix.
const bool isComponentWithin (const Component &component) const
Determines if component within.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
virtual void log (el::base::type::ostream_t &os) const override
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for camera.
Constructor & Destructor Documentation
Graphics::Camera::Camera () delete
Graphics::Camera::Camera (const std::shared_ptr< ShaderManager > shader_manager)
Constructor for Camera.
Parameters
[in] shader_manager The shader manager
Graphics::Camera::Camera (const std::shared_ptr< ShaderManager > shader_manager, const float viewport_width, const float viewport_height, const float near = 0.1, const float far = 1.0)
Constructor for Camera.
Parameters
[in] shader_manager The shader manager
[in] viewport_width The viewport width
[in] viewport_height The viewport height
[in] near The near plane z value
[in] far The far plane z value
Member Function Documentation
const std::string Graphics::Camera::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Referenced by generated::getCameraModule().
const float Graphics::Camera::getFar () const noexcept
Gets the far z plane.
Returns
The far.
Referenced by generated::getCameraModule().
const float Graphics::Camera::getFreeCameraSpeed () const noexcept
Gets the free camera speed when in free camera mode.
Returns
The free camera speed.
Referenced by generated::getCameraModule().
const float Graphics::Camera::getHeight () const noexcept
Gets the height.
Returns
The height.
Referenced by generated::getCameraModule().
const float Graphics::Camera::getNear () const noexcept
Gets the near z plane.
Returns
The near.
Referenced by generated::getCameraModule().
const glm::mat4 Graphics::Camera::getProjectionMatrix () const noexcept
Gets the projection matrix.
Returns
The projection matrix.
Referenced by generated::getCameraModule(), and Engine::setup().
const int Graphics::Camera::getScreenPaddingInTiles () const noexcept
Gets the screen padding in tiles.
Returns
The screen padding in tiles.
Referenced by generated::getCameraModule().
const unsigned long long Graphics::Camera::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
References Component::getId().
const float Graphics::Camera::getWidth () const noexcept
Gets the width.
Returns
The width.
Referenced by generated::getCameraModule().
void Graphics::Camera::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
References Component::getTransform(), Component::handleQueuedEvent(), Events::KEY_DOWN, Events::KEY_REPEAT, Events::KEY_UP, and Events::SPRITE_MOVE.
Referenced by onNotifyNow().
const bool Graphics::Camera::isComponentWithin (const Component & component) const
Determines if component within.
Parameters
[in] component The component
Returns
True if component within, False otherwise.
References Component::getTransform().
Referenced by generated::getCameraModule().
void Graphics::Camera::log (el::base::type::ostream_t & os) const override virtual
Reimplemented from Component.
References Component::log().
void Graphics::Camera::onDestroy () override virtual
Called when the engine is shutting down.
Implements Component.
void Graphics::Camera::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
References handleQueuedEvent().
void Graphics::Camera::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
References Graphics::UI::ChangeTextEvent::create(), Transform::getAbsoluteTransformationMatrix(), Component::getTransform(), and Events::Subject::notify().
const bool Graphics::Camera::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
References Component::active, Graphics::UI::ChangeTextEvent::create(), Transform::getAbsoluteTransformationMatrix(), Component::getTransform(), and Events::Subject::notify().
void Graphics::Camera::setFar (const float far) noexcept
Sets the far z plane.
Parameters
[in] far The far
Referenced by generated::getCameraModule().
void Graphics::Camera::setFreeCameraSpeed (const float speed) noexcept
Sets the free camera speed when in free camera mode.
Parameters
[in] speed The speed
Referenced by generated::getCameraModule().
void Graphics::Camera::setHeight (const float height) noexcept
Sets the height.
Parameters
[in] height The height
Referenced by generated::getCameraModule().
void Graphics::Camera::setNear (const float near) noexcept
Sets the near z plane.
Parameters
[in] near The near
Referenced by generated::getCameraModule().
void Graphics::Camera::setScreenPaddingInTiles (const int padding) noexcept
Sets the screen padding in tiles.
Parameters
[in] padding The padding
Referenced by generated::getCameraModule().
void Graphics::Camera::setWidth (const float width) noexcept
Sets the width.
Parameters
[in] width The width
Referenced by generated::getCameraModule().
The documentation for this class was generated from the following files:
src/graphics/camera.h
src/graphics/camera.cpp