Nymph Game Engine: Graphics::GraphicsSystem Class Reference
Graphics::GraphicsSystem Class Reference
Class for graphics system.
#include <graphics_system.h>
Public Member Functions
GraphicsSystem ()
~GraphicsSystem ()
void initialize (const int width, const int height, std::string name, const bool fullscreen, const WindowExitFunctor &window_exit)
Initializes the graphics system.
const bool isInitialized () const noexcept
Getter to see if system is initialized.
const bool isRunning () noexcept
Determines if running.
void startRender ()
Starts a render.
void stopRender ()
Stops a render.
void startFrame ()
Starts a frame.
void stopFrame ()
Stops a frame.
GLFWwindow * getWindow () const noexcept
Gets the window.
const int windowHeight ()
Getter for the window width.
const int windowWidth ()
Getter for the window height.
const std::string windowName () const noexcept
Getter for the window name.
void setWindowName (const std::string &name)
Sets the window name.
const int addRenderable (std::shared_ptr< Graphics::Renderable > renderable)
Adds a renderable to the renderable pool.
const bool removeRenderable (const int id)
Removes a renderable from the renderable pool.
const int renderablesCount ()
Returns the number of renderables currently in the system.
void setMaxInfluenceLights (const unsigned int number) noexcept
Sets the maximum number influencing lights.
const unsigned int getMaxInfluenceLights () const noexcept
Gets the maximum number of influencing lights.
void addLight (std::shared_ptr< Light > light) noexcept
Adds a light.
void removeLight (std::shared_ptr< Light > light)
Removes a light.
GLFWwindow * getCurrentWindow () noexcept
void destroy ()
Closes window, and destroys GLFW context.
Detailed Description
Class for graphics system.
Constructor & Destructor Documentation
Graphics::GraphicsSystem::GraphicsSystem ()
Graphics::GraphicsSystem::~GraphicsSystem ()
References destroy().
Member Function Documentation
void Graphics::GraphicsSystem::addLight (std::shared_ptr< Light > light) noexcept
Adds a light.
Parameters
[in] light The light
Referenced by generated::getGraphicsSystemModule().
const int Graphics::GraphicsSystem::addRenderable (std::shared_ptr< Graphics::Renderable > renderable)
Adds a renderable to the renderable pool.
Added to the pool of renderables that can be rendered during the update loop.
Parameters
renderable Shared Pointer to a previously created renderable
Returns
id integer of the renderable
Referenced by generated::getGraphicsSystemModule().
void Graphics::GraphicsSystem::destroy ()
Closes window, and destroys GLFW context.
This closes the window created by GLFW and terminates glfw. Initialize must be called to get another window.
Referenced by ~GraphicsSystem().
GLFWwindow * Graphics::GraphicsSystem::getCurrentWindow () noexcept
const unsigned int Graphics::GraphicsSystem::getMaxInfluenceLights () const noexcept
Gets the maximum number of influencing lights.
Returns
The maximum influence lights.
Referenced by generated::getGraphicsSystemModule().
GLFWwindow * Graphics::GraphicsSystem::getWindow () const noexcept
Gets the window.
Returns
The window.
Referenced by Engine::setup().
void Graphics::GraphicsSystem::initialize (const int width, const int height, std::string name, const bool fullscreen, const WindowExitFunctor & window_exit)
Initializes the graphics system.
This function initializes the graphics system by creating a GLFW based window at the specified size, and having the supplied name as the window title. Max FPS can also be supplied to allow VSYNC.
Parameters
width window width in px
height window height in px
name string containing the name of the window to be built
max_fps double containing the max allowed fps. Default 0.0.
const bool Graphics::GraphicsSystem::isInitialized () const noexcept
Getter to see if system is initialized.
Will return true after initialize() is called.
Returns
true if initialized() has been called, false otherwise
const bool Graphics::GraphicsSystem::isRunning () noexcept
Determines if running.
Returns
True if running, False otherwise.
void Graphics::GraphicsSystem::removeLight (std::shared_ptr< Light > light)
Removes a light.
Parameters
[in] light The light
Referenced by generated::getGraphicsSystemModule().
const bool Graphics::GraphicsSystem::removeRenderable (const int id)
Removes a renderable from the renderable pool.
Removed from the pool of renderables to take it out of the update loop.
Parameters
id id integer of renderable to remove
Returns
true if successful, false if it didn't exist
Referenced by generated::getGraphicsSystemModule().
const int Graphics::GraphicsSystem::renderablesCount ()
Returns the number of renderables currently in the system.
This returns the number of renderables that have been added to the system, and are ready to be updated and rendered.
Returns
integer representing number of renderables in the system
Referenced by generated::getGraphicsSystemModule().
void Graphics::GraphicsSystem::setMaxInfluenceLights (const unsigned int number) noexcept
Sets the maximum number influencing lights.
Parameters
[in] number The number
Referenced by generated::getGraphicsSystemModule().
void Graphics::GraphicsSystem::setWindowName (const std::string & name)
Sets the window name.
Parameters
[in] name The name
Referenced by generated::getGraphicsSystemModule().
void Graphics::GraphicsSystem::startFrame ()
Starts a frame.
void Graphics::GraphicsSystem::startRender ()
Starts a render.
void Graphics::GraphicsSystem::stopFrame ()
Stops a frame.
void Graphics::GraphicsSystem::stopRender ()
Stops a render.
const int Graphics::GraphicsSystem::windowHeight ()
Getter for the window width.
This Pings GLFW to get the width of the window.
Returns
integer denoting pixel width of window
Referenced by generated::getGraphicsSystemModule().
const std::string Graphics::GraphicsSystem::windowName () const noexcept
Getter for the window name.
This will return the name of the window
Returns
a string that is the name of the window
Referenced by generated::getGraphicsSystemModule().
const int Graphics::GraphicsSystem::windowWidth ()
Getter for the window height.
This Pings GLFW to get the height of the window.
Returns
integer denoting pixel height of window
Referenced by generated::getGraphicsSystemModule().
The documentation for this class was generated from the following files:
src/graphics/graphics_system.h
src/graphics/graphics_system.cpp