Nymph Game Engine: Graphics::UI::Element Class Reference
Graphics::UI::Element Class Reference abstract
#include <element.h>
Public Member Functions
Element (VertexData vertex_data, std::shared_ptr< Skin > skin)
Element constructor.
virtual ~Element ()
Destroys element.
std::shared_ptr< Skin > getSkin () const noexcept
Gets the UI skin.
void setSkin (std::shared_ptr< Skin > skin) noexcept
Sets the UI skin.
const glm::vec2 getAnchorPoint () const noexcept
Gets the anchor point.
void setAnchorPoint (const glm::vec2 anchor_point)
Sets the anchor point.
const float getWidth () const noexcept
Gets the width.
const float getHeight () const noexcept
Gets the height.
void setWidth (const float width) noexcept
Sets the width.
void setHeight (const float height) noexcept
Sets the height.
const float getTextPadding () const noexcept
Gets the text padding.
void setTextPadding (const float text_padding) noexcept
Sets the text padding.
const glm::vec4 getColor () const noexcept
Gets the color.
void setColor (const glm::vec4 color) noexcept
Sets the color.
const std::string to_string () const noexcept
bool isPointWithin (glm::vec2 point) noexcept
Determines if point is within element.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onDestroy () override
Called when the engine is shutting down.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void onLeftClick ()=0
Called when element is left clicked.
virtual void onRightClick ()=0
Called when element is right clicked.
virtual void onLeftClickRelease ()=0
Called when element has left click released over it.
virtual void onRightClickRelease ()=0
Called when element has right click released over it.
virtual void onCursorEnter ()=0
Called when the mosue cursor goes over the element.
virtual void onCursorLeave ()=0
Called when the mouse cursor goes off the element.
virtual void onKeyDown (const int key)=0
Called when a key is pressed while element is in focus.
virtual void onKeyUp (const int key)=0
Called when a key is released while element is in focus.
virtual void onKeyRepeat (const int key)=0
Called when a key is repeated while element is in focus.
virtual void onScroll (const glm::dvec2 position_change)=0
Called when the mouse wheel is scrolled while element is in focus.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Graphics::Renderable
Renderable (const unsigned int vertex_array_object, const VertexData &vertex_data)
Renderable constructor.
Renderable (const Renderable &)=delete
Renderable operator= (Renderable &)=delete
Renderable (Renderable &&renderable)
Renderable & operator= (Renderable &&renderable)
virtual ~Renderable ()
void setShader (std::shared_ptr< Shader > shader_object) noexcept
Sets the shader.
const std::shared_ptr< Shader > getShader () const noexcept
Gets the shader.
void addTexture (const unsigned int unit, const std::string uniform_name, std::shared_ptr< BaseTexture > texture_object) noexcept
Adds a texture.
void removeTexture (const unsigned int unit)
Removes a texture.
const std::map< unsigned int, std::shared_ptr< BaseTexture > > getTextures () const noexcept
Gets the textures.
void setLightReactive (const bool reactive) noexcept
Sets if the renderable should be light reactive.
const bool isLightReactive () const noexcept
Determines if light reactive.
void setAmbientLight (const glm::vec3 color) noexcept
Sets the ambient light.
const glm::vec3 getAmbientLight () const noexcept
Gets the ambient light.
void setAmbientIntensity (const float intensity) noexcept
Sets the ambient intensity.
const float getAmbientIntensity () const noexcept
Gets the ambient intensity.
void addInfluencingLight (std::shared_ptr< Light > light) noexcept
Adds an influencing light.
void clearInfluencingLights ()
Clears all influencing lights.
const std::string to_string () const noexcept
Returns a string representation of the object.
const float highestZ () const noexcept
The highest possible z value in the renderable.
const unsigned int getVertexArrayBinding () const noexcept
Gets the vertex array binding.
const VertexData getVertexData () const noexcept
Gets the vertex data.
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Static Protected Member Functions
static std::vector< glm::vec3 > generateRect (float screen_width, float screen_height, float x_pos, float y_pos, float width, float height) noexcept
static std::vector< glm::vec2 > basisTexCoords () noexcept
Additional Inherited Members
Static Public Member Functions inherited from Graphics::Renderable
static std::shared_ptr< Renderable > create (const VertexData &vertex_data)
Renderable factory function.
Protected Member Functions inherited from Graphics::Renderable
void setUniform (const Uniform &uniform) noexcept
Renderable ()
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes inherited from Graphics::Renderable
std::set< Uniform > uniforms
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Constructor & Destructor Documentation
Graphics::UI::Element::Element (VertexData vertex_data, std::shared_ptr< Skin > skin)
Element constructor.
Parameters
[in] vertex_data The vertex data
[in] skin The UI skin
References Graphics::Renderable::addTexture(), and Graphics::Renderable::setShader().
Graphics::UI::Element::~Element () virtual
Destroys element.
Member Function Documentation
std::vector< glm::vec2 > Graphics::UI::Element::basisTexCoords () static protected noexcept
Referenced by Graphics::UI::Area::create(), Graphics::UI::QuitButton::create(), Graphics::UI::Button::create(), Graphics::UI::TextArea::create(), and Graphics::UI::TextField::create().
const std::string Graphics::UI::Element::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, Graphics::UI::Area, and Graphics::UI::QuitButton.
Referenced by generated::getElementModule().
std::vector< glm::vec3 > Graphics::UI::Element::generateRect (float screen_width, float screen_height, float x_pos, float y_pos, float width, float height) static protected noexcept
Referenced by Graphics::UI::Area::create(), Graphics::UI::QuitButton::create(), Graphics::UI::Button::create(), Graphics::UI::TextArea::create(), and Graphics::UI::TextField::create().
const glm::vec2 Graphics::UI::Element::getAnchorPoint () const noexcept
Gets the anchor point.
Returns
The anchor point.
Referenced by generated::getElementModule(), and Graphics::UI::TextArea::onStart().
const glm::vec4 Graphics::UI::Element::getColor () const noexcept
Gets the color.
Returns
The color.
Referenced by generated::getElementModule(), Graphics::UI::Button::onCursorEnter(), Graphics::UI::TextField::onCursorEnter(), Graphics::UI::Button::onCursorLeave(), and Graphics::UI::TextField::onCursorLeave().
const float Graphics::UI::Element::getHeight () const noexcept
Gets the height.
Returns
The height.
Referenced by generated::getElementModule().
std::shared_ptr< Skin > Graphics::UI::Element::getSkin () const noexcept
Gets the UI skin.
Returns
The skin.
Referenced by generated::getElementModule().
const float Graphics::UI::Element::getTextPadding () const noexcept
Gets the text padding.
Returns
The text padding.
Referenced by generated::getElementModule().
const unsigned long long Graphics::UI::Element::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
const float Graphics::UI::Element::getWidth () const noexcept
Gets the width.
Returns
The width.
Referenced by generated::getElementModule().
void Graphics::UI::Element::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextArea, and Graphics::UI::TextField.
References Graphics::Renderable::handleQueuedEvent(), Component::isActive(), isPointWithin(), Events::KEY_DOWN, Events::KEY_REPEAT, Events::KEY_UP, Events::MOUSE_BUTTON_DOWN, Events::MOUSE_BUTTON_UP, Events::MOUSE_CURSOR, Events::MOUSE_SCROLL, onCursorEnter(), onCursorLeave(), onKeyDown(), onKeyRepeat(), onKeyUp(), onLeftClick(), onLeftClickRelease(), onRightClick(), onRightClickRelease(), and onScroll().
Referenced by Graphics::UI::Area::handleQueuedEvent(), and onNotifyNow().
bool Graphics::UI::Element::isPointWithin (glm::vec2 point) noexcept
Determines if point is within element.
Parameters
[in] point The point
Returns
True if point within, False otherwise.
Referenced by generated::getElementModule(), and handleQueuedEvent().
void Graphics::UI::Element::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Area, and Graphics::UI::Button.
References to_string().
virtual void Graphics::UI::Element::onCursorEnter () pure virtual
Called when the mosue cursor goes over the element.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onCursorLeave () pure virtual
Called when the mouse cursor goes off the element.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
void Graphics::UI::Element::onDestroy () override virtual
Called when the engine is shutting down.
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
Referenced by Graphics::UI::Area::onDestroy().
virtual void Graphics::UI::Element::onKeyDown (const int key) pure virtual
Called when a key is pressed while element is in focus.
Parameters
[in] key The key
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onKeyRepeat (const int key) pure virtual
Called when a key is repeated while element is in focus.
Parameters
[in] key The key
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onKeyUp (const int key) pure virtual
Called when a key is released while element is in focus.
Parameters
[in] key The key
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onLeftClick () pure virtual
Called when element is left clicked.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, Graphics::UI::Area, and Graphics::UI::QuitButton.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onLeftClickRelease () pure virtual
Called when element has left click released over it.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
void Graphics::UI::Element::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextArea, and Graphics::UI::TextField.
References handleQueuedEvent().
virtual void Graphics::UI::Element::onRightClick () pure virtual
Called when element is right clicked.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onRightClickRelease () pure virtual
Called when element has right click released over it.
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
virtual void Graphics::UI::Element::onScroll (const glm::dvec2 position_change) pure virtual
Called when the mouse wheel is scrolled while element is in focus.
Parameters
[in] position_change The position change
Implemented in Graphics::UI::TextArea, Graphics::UI::TextField, Graphics::UI::Button, and Graphics::UI::Area.
Referenced by handleQueuedEvent().
void Graphics::UI::Element::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
Referenced by Graphics::UI::Area::onStart().
const bool Graphics::UI::Element::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Reimplemented from Graphics::Renderable.
Reimplemented in Graphics::UI::TextField, Graphics::UI::TextArea, and Graphics::UI::Area.
References Graphics::Renderable::onUpdate().
Referenced by Graphics::UI::Area::onUpdate().
void Graphics::UI::Element::setAnchorPoint (const glm::vec2 anchor_point)
Sets the anchor point.
Parameters
[in] anchor_point The anchor point
References Graphics::Renderable::setUniform().
Referenced by generated::getElementModule().
void Graphics::UI::Element::setColor (const glm::vec4 color) noexcept
Sets the color.
Parameters
[in] color The color
Referenced by generated::getElementModule(), Graphics::UI::Button::onCursorEnter(), Graphics::UI::TextField::onCursorEnter(), Graphics::UI::Button::onCursorLeave(), Graphics::UI::TextField::onCursorLeave(), Graphics::UI::Button::onLeftClick(), and Graphics::UI::Button::onLeftClickRelease().
void Graphics::UI::Element::setHeight (const float height) noexcept
Sets the height.
Parameters
[in] height The height
Referenced by generated::getElementModule().
void Graphics::UI::Element::setSkin (std::shared_ptr< Skin > skin) noexcept
Sets the UI skin.
Parameters
[in] skin The skin
Referenced by generated::getElementModule().
void Graphics::UI::Element::setTextPadding (const float text_padding) noexcept
Sets the text padding.
Parameters
[in] text_padding The text padding
Referenced by generated::getElementModule(), and Graphics::UI::QuitButton::QuitButton().
void Graphics::UI::Element::setWidth (const float width) noexcept
Sets the width.
Parameters
[in] width The width
Referenced by generated::getElementModule().
const std::string Graphics::UI::Element::to_string () const noexcept
References Graphics::Renderable::to_string().
Referenced by generated::getElementModule(), log(), and Graphics::UI::Area::to_string().
The documentation for this class was generated from the following files:
src/graphics/ui/element.h
src/graphics/ui/element.cpp