Nymph Game Engine: Graphics::UI::Text Class Reference
Graphics::UI::Text Class Reference
Class for text.
#include <text.h>
Public Member Functions
Text ()
Constructor for Text.
void setFont (const std::shared_ptr< Font > font)
Sets the font.
virtual void setText (const std::string &text)
Sets the text string.
const std::string getText () const noexcept
Gets the text string.
void setColor (const glm::vec4 &color)
Sets the color.
const glm::vec4 getColor () const noexcept
Gets the color.
void setShader (std::shared_ptr< Shader > shader)
Sets the shader.
void setKerning (const float amount) noexcept
Sets the kerning.
const float getKerning () const noexcept
Gets the kerning.
const std::string to_string () const noexcept
Returns a string representation of the object.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onDestroy () override
Called when the engine is shutting down.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Protected Member Functions
void renderCharacter (const unsigned char character, Transform transform)
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Protected Attributes
std::shared_ptr< Font > font
std::string text
glm::vec4 color
std::shared_ptr< Shader > shader
float kerning
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Additional Inherited Members
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for text.
Constructor & Destructor Documentation
Graphics::UI::Text::Text ()
Constructor for Text.
Member Function Documentation
const std::string Graphics::UI::Text::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Component.
Reimplemented in Graphics::UI::WrappableText.
Referenced by generated::getTextModule().
const glm::vec4 Graphics::UI::Text::getColor () const noexcept
Gets the color.
Returns
The color.
References color.
Referenced by generated::getTextModule().
const float Graphics::UI::Text::getKerning () const noexcept
Gets the kerning.
Returns
The kerning.
References kerning.
Referenced by generated::getTextModule().
const std::string Graphics::UI::Text::getText () const noexcept
Gets the text string.
Returns
The text string.
References text.
Referenced by generated::getTextModule().
const unsigned long long Graphics::UI::Text::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Implements Component.
Reimplemented in Graphics::UI::WrappableText.
void Graphics::UI::Text::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Component.
Reimplemented in Graphics::UI::WrappableText.
References Component::handleQueuedEvent().
Referenced by onNotifyNow().
void Graphics::UI::Text::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Component.
Reimplemented in Graphics::UI::WrappableText.
References to_string().
void Graphics::UI::Text::onDestroy () override virtual
Called when the engine is shutting down.
Implements Component.
Reimplemented in Graphics::UI::WrappableText.
void Graphics::UI::Text::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Component.
Reimplemented in Graphics::UI::WrappableText.
References handleQueuedEvent().
void Graphics::UI::Text::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Implements Component.
Reimplemented in Graphics::UI::WrappableText.
const bool Graphics::UI::Text::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Implements Component.
Reimplemented in Graphics::UI::WrappableText.
References color, font, Component::getTransform(), Component::isActive(), kerning, renderCharacter(), Graphics::Uniform::setData(), shader, and text.
void Graphics::UI::Text::renderCharacter (const unsigned char character, Transform transform) protected
References font, Transform::getAbsoluteTransformationMatrix(), Component::getTransform(), Graphics::Uniform::setData(), and shader.
Referenced by Graphics::UI::WrappableText::onUpdate(), and onUpdate().
void Graphics::UI::Text::setColor (const glm::vec4 & color)
Sets the color.
Parameters
[in] color The color
References color.
Referenced by generated::getTextModule().
void Graphics::UI::Text::setFont (const std::shared_ptr< Font > font)
Sets the font.
Parameters
[in] font The font
References font.
Referenced by generated::getTextModule().
void Graphics::UI::Text::setKerning (const float amount) noexcept
Sets the kerning.
Parameters
[in] amount The amount
Referenced by generated::getTextModule().
void Graphics::UI::Text::setShader (std::shared_ptr< Shader > shader)
Sets the shader.
Parameters
[in] shader The shader
References shader.
Referenced by generated::getTextModule().
void Graphics::UI::Text::setText (const std::string & text) virtual
Sets the text string.
Parameters
[in] text The text string
Reimplemented in Graphics::UI::WrappableText.
References text.
Referenced by generated::getTextModule().
const std::string Graphics::UI::Text::to_string () const noexcept
Returns a string representation of the object.
Returns
String representation of the object.
References color, kerning, text, and Component::to_string().
Referenced by generated::getTextModule(), log(), and Graphics::UI::WrappableText::to_string().
Member Data Documentation
glm::vec4 Graphics::UI::Text::color protected
Referenced by getColor(), Graphics::UI::WrappableText::onUpdate(), onUpdate(), setColor(), and to_string().
std::shared_ptr<Font> Graphics::UI::Text::font protected
Referenced by onUpdate(), renderCharacter(), setFont(), Graphics::UI::WrappableText::setText(), and Graphics::UI::WrappableText::splitTextIntoLines().
float Graphics::UI::Text::kerning protected
Referenced by getKerning(), onUpdate(), Graphics::UI::WrappableText::setText(), Graphics::UI::WrappableText::splitTextIntoLines(), and to_string().
std::shared_ptr<Shader> Graphics::UI::Text::shader protected
Referenced by Graphics::UI::WrappableText::onUpdate(), onUpdate(), renderCharacter(), and setShader().
std::string Graphics::UI::Text::text protected
Referenced by getText(), onUpdate(), setText(), Graphics::UI::WrappableText::setText(), Graphics::UI::WrappableText::splitTextIntoLines(), and to_string().
The documentation for this class was generated from the following files:
src/graphics/ui/text.h
src/graphics/ui/text.cpp