Nymph Game Engine: Utility::DebugParser Class Reference
Utility::DebugParser Class Reference
Class for debug parser.
#include <debug_parser.h>
Public Member Functions
void onNotifyNow (std::shared_ptr< Events::Event > event)
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
void handleQueuedEvent (std::shared_ptr< Events::Event > event)
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
DebugParser ()=default
DebugParser constructor.
void parseCommand (const std::string &command)
Parses a debug command.
void handleEvents ()
Handles queued debug parser events.
virtual ~DebugParser ()=default
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Detailed Description
Class for debug parser.
Constructor & Destructor Documentation
Utility::DebugParser::DebugParser () default
DebugParser constructor.
virtual Utility::DebugParser::~DebugParser () virtual default
Destroys the object.
Member Function Documentation
void Utility::DebugParser::handleEvents ()
Handles queued debug parser events.
Must be called every engine loop to get events out of the event queue and use them
References Events::Observer::processEventQueue().
Referenced by generated::getDebugParserModule().
void Utility::DebugParser::handleQueuedEvent (std::shared_ptr< Events::Event > event) virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Implements Events::Observer.
References Events::DEBUG_COMMAND, and parseCommand().
Referenced by onNotifyNow().
void Utility::DebugParser::onNotifyNow (std::shared_ptr< Events::Event > event) virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Implements Events::Observer.
References handleQueuedEvent().
void Utility::DebugParser::parseCommand (const std::string & command)
Parses a debug command.
Parameters
[in] command The command
References Utility::ListMapsEvent::create(), Utility::ListCharactersEvent::create(), Utility::ListLayersEvent::create(), Utility::ToggleFreeCameraEvent::create(), Utility::WindowExitEvent::create(), Utility::ToggleLightsEvent::create(), Utility::LoadCharacterEvent::create(), Utility::LoadMapEvent::create(), Utility::ToggleLayerEvent::create(), and Events::Subject::notify().
Referenced by generated::getDebugParserModule(), and handleQueuedEvent().
The documentation for this class was generated from the following files:
src/utility/debug_parser.h
src/utility/debug_parser.cpp