Nymph Game Engine: Input::InputSystem Class Reference
Input::InputSystem Class Reference
Class for input system.
#include <input_system.h>
Public Member Functions
virtual ~InputSystem ()=default
InputSystem (GLFWwindow *window, float viewport_width, float viewport_height, glm::mat4 camera_transform_matrix, glm::mat4 projection_matrix)
Constructor for input system.
void pollForInput ()
Polls glfw for new input.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Detailed Description
Class for input system.
Constructor & Destructor Documentation
virtual Input::InputSystem::~InputSystem () virtual default
Input::InputSystem::InputSystem (GLFWwindow * window, float viewport_width, float viewport_height, glm::mat4 camera_transform_matrix, glm::mat4 projection_matrix)
Constructor for input system.
Parameters
window The window
[in] viewport_width The viewport width
[in] viewport_height The viewport height
[in] camera_transform_matrix The camera transform matrix
[in] projection_matrix The projection matrix
Member Function Documentation
void Input::InputSystem::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Implements Events::Observer.
References Events::RESUME_KEY_INPUT, and Events::SUSPEND_KEY_INPUT.
Referenced by onNotifyNow().
void Input::InputSystem::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Implements Events::Observer.
References handleQueuedEvent().
void Input::InputSystem::pollForInput ()
Polls glfw for new input.
References Input::CursorLeaveEvent::create(), Input::CursorEnterEvent::create(), Input::MouseButtonDownEvent::create(), Input::KeyRepeatEvent::create(), Input::CharacterTypedEvent::create(), Input::KeyDownEvent::create(), Input::MouseCursorEvent::create(), Input::MouseScrollEvent::create(), Input::KeyUpEvent::create(), Input::MouseButtonUpEvent::create(), and Events::Subject::notify().
The documentation for this class was generated from the following files:
src/input/input_system.h
src/input/input_system.cpp