Nymph Game Engine: Input::MouseCursorEvent Class Reference
Input::MouseCursorEvent Class Reference
Class for mouse cursor event.
#include <mouse_cursor_event.h>
Public Member Functions
MouseCursorEvent (const glm::dvec2 &pos)
MouseCursorEvent constructor.
const glm::dvec2 getPosition () const noexcept
Gets the position.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
const EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr< MouseCursorEvent > create (const glm::dvec2 &pos)
Factory function.
Detailed Description
Class for mouse cursor event.
Constructor & Destructor Documentation
Input::MouseCursorEvent::MouseCursorEvent (const glm::dvec2 & pos) inline
MouseCursorEvent constructor.
Parameters
[in] pos The position
Member Function Documentation
static std::shared_ptr<MouseCursorEvent> Input::MouseCursorEvent::create (const glm::dvec2 & pos) inline static
Factory function.
Parameters
[in] pos The position
Returns
Newly created MouseCursorEvent
Referenced by generated::getMouseCursorEventModule(), and Input::InputSystem::pollForInput().
const glm::dvec2 Input::MouseCursorEvent::getPosition () const inline noexcept
Gets the position.
Returns
The position.
Referenced by generated::getMouseCursorEventModule().
The documentation for this class was generated from the following file:
src/input/mouse_cursor_event.h