Nymph Game Engine: ComponentManager Class Reference
ComponentManager Class Reference
Class for component manager.
#include <component_manager.h>
Public Member Functions
void addComponent (std::shared_ptr< Component > component)
Adds a component.
void addComponents (std::vector< std::shared_ptr< Component >> components)
Adds components.
void addComponents (std::list< std::shared_ptr< Component >> components)
Adds components.
void removeComponent (std::shared_ptr< Component > component)
Removes a component.
void removeComponents (std::vector< std::shared_ptr< Component >> components)
Removes components.
const unsigned int count () const noexcept
Gets the number of components.
void addComponent (std::shared_ptr< Graphics::Camera > component)
Adds a camera.
void onStart ()
Calls onStart on each component.
void onUpdate (const float delta)
Calls onUpdate on each component, once per frame.
void destroy ()
Calls onDestroy on each component.
Detailed Description
Class for component manager.
Member Function Documentation
void ComponentManager::addComponent (std::shared_ptr< Component > component)
Adds a component.
Parameters
[in] component The component
References Entity::components.
Referenced by generated::getComponentManagerModule(), and Engine::setup().
void ComponentManager::addComponent (std::shared_ptr< Graphics::Camera > component)
Adds a camera.
Parameters
[in] component The component
References Entity::components.
void ComponentManager::addComponents (std::vector< std::shared_ptr< Component >> components)
Adds components.
Parameters
[in] components The components
References Entity::components.
Referenced by generated::getComponentManagerModule().
void ComponentManager::addComponents (std::list< std::shared_ptr< Component >> components)
Adds components.
Parameters
[in] components The components
References Entity::components.
const unsigned int ComponentManager::count () const noexcept
Gets the number of components.
Returns
# of components
References Entity::components.
Referenced by generated::getComponentManagerModule().
void ComponentManager::destroy ()
Calls onDestroy on each component.
References Entity::components.
void ComponentManager::onStart ()
Calls onStart on each component.
References Entity::components.
void ComponentManager::onUpdate (const float delta)
Calls onUpdate on each component, once per frame.
Parameters
[in] delta The delta
References Entity::components.
void ComponentManager::removeComponent (std::shared_ptr< Component > component)
Removes a component.
Parameters
[in] component The component
References Entity::components.
Referenced by generated::getComponentManagerModule(), and removeComponents().
void ComponentManager::removeComponents (std::vector< std::shared_ptr< Component >> components)
Removes components.
Parameters
[in] components The components
References Entity::components, and removeComponent().
Referenced by generated::getComponentManagerModule().
The documentation for this class was generated from the following files:
src/component_manager.h
src/component_manager.cpp