Nymph Game Engine: Graphics::UI::Font Class Reference
Graphics::UI::Font Class Reference
Class for font.
#include <font.h>
Public Member Functions
Font (const unsigned int size=12, const unsigned int pixels_per_unit=32)
Font constructor.
void addCharacter (const char text_char, const Character &character)
Adds a character.
Character getCharacter (const char text_char)
Gets the character.
std::map< char, Character > getCharacters () const
Gets the characters.
const unsigned int getSize () const noexcept
Gets the size.
const float getOpenGLSize () const noexcept
Gets the open gl size.
Detailed Description
Class for font.
Constructor & Destructor Documentation
Graphics::UI::Font::Font (const unsigned int size = 12, const unsigned int pixels_per_unit = 32)
Font constructor.
Parameters
[in] size The size
[in] pixels_per_unit The pixels per unit
Member Function Documentation
void Graphics::UI::Font::addCharacter (const char text_char, const Character & character)
Adds a character.
Parameters
[in] text_char The text character
[in] character The engine character
Referenced by generated::getFontModule().
Character Graphics::UI::Font::getCharacter (const char text_char)
Gets the character.
Parameters
[in] text_char The text character
Returns
The character.
Referenced by generated::getFontModule().
std::map< char, Character > Graphics::UI::Font::getCharacters () const
Gets the characters.
Returns
The characters.
Referenced by generated::getFontModule().
const float Graphics::UI::Font::getOpenGLSize () const noexcept
Gets the open gl size.
Returns
The open gl size.
Referenced by generated::getFontModule().
const unsigned int Graphics::UI::Font::getSize () const noexcept
Gets the size.
Returns
The size.
Referenced by generated::getFontModule().
The documentation for this class was generated from the following files:
src/graphics/ui/font.h
src/graphics/ui/font.cpp