Nymph Game Engine: Script::ScriptObject Class Reference
Script::ScriptObject Class Reference
Class for script object.
#include <script_object.hpp>
Public Member Functions
ScriptObject ()=delete
ScriptObject (const std::string &name, std::shared_ptr< chaiscript::ChaiScript > chai_interpreter)
ScriptObject constructor.
ScriptObject (const ScriptObject &other)
Copy constructor for ScriptObject.
~ScriptObject ()=default
Destroys the object.
void setClassName (const std::string &name)
Sets the class name on the scripting object.
void onStart ()
Calls onStart in the attached script object.
void onUpdate (const float delta)
Calls onUpdate in the attached script object.
void onDestroy ()
Calls onDestroy in the attached script object.
virtual void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
template<class T >
std::enable_if< std::is_base_of< Events::Event, T >::value, std::function< void(chaiscript::Boxed_Value &, std::shared_ptr< T >)> >::type selectEventHandler ()
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Additional Inherited Members
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Detailed Description
Class for script object.
Constructor & Destructor Documentation
Script::ScriptObject::ScriptObject () delete
Script::ScriptObject::ScriptObject (const std::string & name, std::shared_ptr< chaiscript::ChaiScript > chai_interpreter)
ScriptObject constructor.
Parameters
[in] name The name
[in] chai_interpreter The chaiscript interpreter
Script::ScriptObject::ScriptObject (const ScriptObject & other)
Copy constructor for ScriptObject.
Parameters
[in] other The other
Script::ScriptObject::~ScriptObject () default
Destroys the object.
Member Function Documentation
void Script::ScriptObject::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Implements Events::Observer.
References Events::ANIMATION_TRIGGER, Events::CHANGE_TEXT, Events::CHARACTER_TYPED, Events::CURSOR_ENTER, Events::CURSOR_LEAVE, Events::DEBUG_COMMAND, Events::KEY_DOWN, Events::KEY_REPEAT, Events::KEY_UP, Events::LIST_CHARACTERS, Events::LIST_LAYERS, Events::LIST_MAPS, Events::LOAD_CHARACTER, Events::LOAD_MAP, Events::MOUSE_BUTTON_DOWN, Events::MOUSE_BUTTON_UP, Events::MOUSE_CURSOR, Events::MOUSE_SCROLL, Events::RESUME_KEY_INPUT, Events::SET_ACTIVE, Events::SET_ENTITY_ACTIVE, Events::SET_UNIFORM, Events::SPRITE_MOVE, Events::SUSPEND_KEY_INPUT, Events::TOGGLE_FREE_CAMERA, Events::TOGGLE_LAYER, Events::TOGGLE_LIGHTS, and Events::WINDOW_EXIT.
Referenced by onNotifyNow().
void Script::ScriptObject::onDestroy ()
Calls onDestroy in the attached script object.
void Script::ScriptObject::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Implements Events::Observer.
References handleQueuedEvent().
void Script::ScriptObject::onStart ()
Calls onStart in the attached script object.
void Script::ScriptObject::onUpdate (const float delta)
Calls onUpdate in the attached script object.
Parameters
[in] delta The delta
References Events::Observer::processEventQueue().
template<class T > std::enable_if<std::is_base_of<Events::Event, T>::value, std::function<void(chaiscript::Boxed_Value&, std::shared_ptr<T>)> >::type Script::ScriptObject::selectEventHandler ()
void Script::ScriptObject::setClassName (const std::string & name)
Sets the class name on the scripting object.
Parameters
[in] name The name
Referenced by generated::getScriptObjectModule().
The documentation for this class was generated from the following files:
src/script/script_object.hpp
src/script/script_object.cpp