Nymph Game Engine: Graphics::ShaderManager Class Reference
Graphics::ShaderManager Class Reference
Class for shader manager.
#include <shader_manager.h>
Public Member Functions
ShaderManager ()
Shader Manager constructor.
~ShaderManager ()
Destroys the object.
const bool loadShader (const std::string &name, const bool geometry_shader=false)
Loads a shader.
const bool loadShader (const std::string &name, const std::string &vertex_filename, const std::string &fragment_filename, const std::string &geometry_filename)
Loads a shader.
std::shared_ptr< Shader > operator[] (const std::string &name) const
looks up shader by name
std::shared_ptr< Shader > getShader (const std::string &name) const
Gets the shader.
void setUniformForAllPrograms (const Uniform &u)
Sets the uniform for all programs.
template<class T >
void setUniformForAllPrograms (const std::string &name, const T &data)
Sets the uniform for all programs.
Static Public Attributes
static char const * VERTEX_EXTENSION = ".vert"
static char const * FRAGMENT_EXTENSION = ".frag"
static char const * GEOMETRY_EXTENSION = ".geom"
static char const * SHADER_DIRECTORY = "./shaders/"
Detailed Description
Class for shader manager.
Constructor & Destructor Documentation
Graphics::ShaderManager::ShaderManager ()
Shader Manager constructor.
Graphics::ShaderManager::~ShaderManager ()
Destroys the object.
Member Function Documentation
std::shared_ptr< Shader > Graphics::ShaderManager::getShader (const std::string & name) const
Gets the shader.
Parameters
[in] name The name
Returns
The shader.
Referenced by generated::getShaderManagerModule(), and operator[]().
const bool Graphics::ShaderManager::loadShader (const std::string & name, const bool geometry_shader = false)
Loads a shader.
Parameters
[in] name The name
[in] geometry_shader The geometry shader
Returns
True if successful
References FRAGMENT_EXTENSION, GEOMETRY_EXTENSION, and VERTEX_EXTENSION.
Referenced by generated::getShaderManagerModule().
const bool Graphics::ShaderManager::loadShader (const std::string & name, const std::string & vertex_filename, const std::string & fragment_filename, const std::string & geometry_filename)
Loads a shader.
Parameters
[in] name The name
[in] vertex_filename The vertex filename
[in] fragment_filename The fragment filename
[in] geometry_filename The geometry filename
Returns
True if successful
References SHADER_DIRECTORY.
std::shared_ptr< Shader > Graphics::ShaderManager::operator[] (const std::string & name) const
looks up shader by name
Parameters
[in] name The name
Returns
Shader with name
References getShader().
void Graphics::ShaderManager::setUniformForAllPrograms (const Uniform & u)
Sets the uniform for all programs.
Parameters
[in] u The uniform to set
Referenced by generated::getShaderManagerModule().
template<class T > void Graphics::ShaderManager::setUniformForAllPrograms (const std::string & name, const T & data)
Sets the uniform for all programs.
Parameters
[in] name The name
[in] data The data
Template Parameters
T The data type for the uniform
Member Data Documentation
char const * Graphics::ShaderManager::FRAGMENT_EXTENSION = ".frag" static
Fragment Shader Extension
Referenced by loadShader().
char const * Graphics::ShaderManager::GEOMETRY_EXTENSION = ".geom" static
Geometry Shader Extension
Referenced by loadShader().
char const * Graphics::ShaderManager::SHADER_DIRECTORY = "./shaders/" static
Shader directory location
Referenced by loadShader().
char const * Graphics::ShaderManager::VERTEX_EXTENSION = ".vert" static
Vertex Shader Extension
Referenced by loadShader().
The documentation for this class was generated from the following files:
src/graphics/shader_manager.h
src/graphics/shader_manager.cpp