Nymph Game Engine: Script::ScriptingSystem Class Reference
Script::ScriptingSystem Class Reference
Class for scripting system.
#include <scripting_system.h>
Public Member Functions
ScriptingSystem ()=delete
ScriptingSystem (const std::string scripts_location)
ScriptingSystem constructor, this registers all modules.
void registerModule (chaiscript::ModulePtr module)
Registers a chaiscript module.
void loadScript (const std::string &name)
Loads a script.
void loadScripts ()
Loads all scripts in scripts location, recursively.
template<class T >
void addObject (std::shared_ptr< T > object, const std::string &name)
Adds an object of type to chaiscript.
template<class T >
void addGlobalObject (std::shared_ptr< T > object, const std::string &name)
Adds a global object of type to chaiscript.
void start ()
Calls onStart in all scripts.
void update (const float delta)
Calls onUpdate in all scripts.
void destroy ()
Calls onDestroy in all scripts.
Detailed Description
Class for scripting system.
Constructor & Destructor Documentation
Script::ScriptingSystem::ScriptingSystem () delete
Script::ScriptingSystem::ScriptingSystem (const std::string scripts_location)
ScriptingSystem constructor, this registers all modules.
Parameters
[in] scripts_location The scripts location
References Script::getGlmModule(), and generated::registerModules().
Member Function Documentation
template<class T > void Script::ScriptingSystem::addGlobalObject (std::shared_ptr< T > object, const std::string & name) inline
Adds a global object of type to chaiscript.
Parameters
[in] object The object
[in] name The name
Template Parameters
T Type of the object to add
template<class T > void Script::ScriptingSystem::addObject (std::shared_ptr< T > object, const std::string & name) inline
Adds an object of type to chaiscript.
Parameters
[in] object The object
[in] name The name
Template Parameters
T Type of the object to add
void Script::ScriptingSystem::destroy ()
Calls onDestroy in all scripts.
void Script::ScriptingSystem::loadScript (const std::string & name)
Loads a script.
Parameters
[in] name The name
Referenced by loadScripts().
void Script::ScriptingSystem::loadScripts ()
Loads all scripts in scripts location, recursively.
References loadScript().
void Script::ScriptingSystem::registerModule (chaiscript::ModulePtr module)
Registers a chaiscript module.
Parameters
[in] module The module
void Script::ScriptingSystem::start ()
Calls onStart in all scripts.
void Script::ScriptingSystem::update (const float delta)
Calls onUpdate in all scripts.
Parameters
[in] delta The delta
The documentation for this class was generated from the following files:
src/script/scripting_system.h
src/script/scripting_system.cpp