Nymph Game Engine: Input::MouseScrollEvent Class Reference
Input::MouseScrollEvent Class Reference
Class for mouse scroll event.
#include <mouse_scroll_event.h>
Public Member Functions
MouseScrollEvent (const glm::dvec2 &offset)
MouseScrollEvent constructor.
const glm::dvec2 getPosition () const noexcept
Gets the position.
Public Member Functions inherited from Events::Event
Event (const EventType &type)
Event constructor.
const EventType getEventType () const
Gets the event type.
Static Public Member Functions
static std::shared_ptr< MouseScrollEvent > create (const glm::dvec2 &offset)
Factory function.
Detailed Description
Class for mouse scroll event.
Constructor & Destructor Documentation
Input::MouseScrollEvent::MouseScrollEvent (const glm::dvec2 & offset) inline
MouseScrollEvent constructor.
Parameters
[in] offset The offset
Member Function Documentation
static std::shared_ptr<MouseScrollEvent> Input::MouseScrollEvent::create (const glm::dvec2 & offset) inline static
Factory function.
Parameters
[in] offset The offset
Returns
Newly created MouseScrollEvent
Referenced by generated::getMouseScrollEventModule(), and Input::InputSystem::pollForInput().
const glm::dvec2 Input::MouseScrollEvent::getPosition () const inline noexcept
Gets the position.
Returns
The position.
Referenced by generated::getMouseScrollEventModule().
The documentation for this class was generated from the following file:
src/input/mouse_scroll_event.h