Nymph Game Engine: Graphics::UI::TextField Class Reference
Graphics::UI::TextField Class Reference
Class for text field.
#include <text_field.h>
Public Member Functions
TextField (std::shared_ptr< WrappableText > default_text, std::shared_ptr< WrappableText > typed_text, VertexData vertex_data, std::shared_ptr< Skin > skin)
TextField constructor.
virtual void onLeftClick () override
Called when element is left clicked.
virtual void onRightClick () override
Called when element is right clicked.
virtual void onLeftClickRelease () override
Called when element has left click released over it.
virtual void onRightClickRelease () override
Called when element has right click released over it.
virtual void onCursorEnter () override
Called when the mosue cursor goes over the element.
virtual void onCursorLeave () override
Called when the mouse cursor goes off the element.
virtual void onKeyDown (const int key) override
Called when a key is pressed while element is in focus.
virtual void onKeyUp (const int key) override
Called when a key is released while element is in focus.
virtual void onKeyRepeat (const int key) override
Called when a key is repeated while element is in focus.
virtual void onScroll (const glm::dvec2 position_change) override
Called when the mouse wheel is scrolled while element is in focus.
virtual void onCharacterTyped (const unsigned char character)
const std::string to_string () const noexcept
Returns a string representation of the object.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onDestroy () override
Called when the engine is shutting down.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Graphics::UI::TextArea
TextArea (std::shared_ptr< WrappableText > text, VertexData vertex_data, std::shared_ptr< Skin > skin)
TextArea constructor.
void setText (std::shared_ptr< WrappableText > text)
Sets the text.
std::shared_ptr< WrappableText > getText () const noexcept
Gets the text.
const std::string to_string () const noexcept
Returns a string representation of the object.
Public Member Functions inherited from Graphics::UI::Area
Area (VertexData vertex_data, std::shared_ptr< Skin > skin)
Area constructor.
const std::string to_string () const noexcept
Public Member Functions inherited from Graphics::UI::Element
Element (VertexData vertex_data, std::shared_ptr< Skin > skin)
Element constructor.
virtual ~Element ()
Destroys element.
std::shared_ptr< Skin > getSkin () const noexcept
Gets the UI skin.
void setSkin (std::shared_ptr< Skin > skin) noexcept
Sets the UI skin.
const glm::vec2 getAnchorPoint () const noexcept
Gets the anchor point.
void setAnchorPoint (const glm::vec2 anchor_point)
Sets the anchor point.
const float getWidth () const noexcept
Gets the width.
const float getHeight () const noexcept
Gets the height.
void setWidth (const float width) noexcept
Sets the width.
void setHeight (const float height) noexcept
Sets the height.
const float getTextPadding () const noexcept
Gets the text padding.
void setTextPadding (const float text_padding) noexcept
Sets the text padding.
const glm::vec4 getColor () const noexcept
Gets the color.
void setColor (const glm::vec4 color) noexcept
Sets the color.
const std::string to_string () const noexcept
bool isPointWithin (glm::vec2 point) noexcept
Determines if point is within element.
Public Member Functions inherited from Graphics::Renderable
Renderable (const unsigned int vertex_array_object, const VertexData &vertex_data)
Renderable constructor.
Renderable (const Renderable &)=delete
Renderable operator= (Renderable &)=delete
Renderable (Renderable &&renderable)
Renderable & operator= (Renderable &&renderable)
virtual ~Renderable ()
void setShader (std::shared_ptr< Shader > shader_object) noexcept
Sets the shader.
const std::shared_ptr< Shader > getShader () const noexcept
Gets the shader.
void addTexture (const unsigned int unit, const std::string uniform_name, std::shared_ptr< BaseTexture > texture_object) noexcept
Adds a texture.
void removeTexture (const unsigned int unit)
Removes a texture.
const std::map< unsigned int, std::shared_ptr< BaseTexture > > getTextures () const noexcept
Gets the textures.
void setLightReactive (const bool reactive) noexcept
Sets if the renderable should be light reactive.
const bool isLightReactive () const noexcept
Determines if light reactive.
void setAmbientLight (const glm::vec3 color) noexcept
Sets the ambient light.
const glm::vec3 getAmbientLight () const noexcept
Gets the ambient light.
void setAmbientIntensity (const float intensity) noexcept
Sets the ambient intensity.
const float getAmbientIntensity () const noexcept
Gets the ambient intensity.
void addInfluencingLight (std::shared_ptr< Light > light) noexcept
Adds an influencing light.
void clearInfluencingLights ()
Clears all influencing lights.
const std::string to_string () const noexcept
Returns a string representation of the object.
const float highestZ () const noexcept
The highest possible z value in the renderable.
const unsigned int getVertexArrayBinding () const noexcept
Gets the vertex array binding.
const VertexData getVertexData () const noexcept
Gets the vertex data.
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Static Public Member Functions
static std::shared_ptr< TextField > create (std::shared_ptr< Skin > skin, std::shared_ptr< WrappableText > default_text, std::shared_ptr< WrappableText > typed_text, glm::vec4 background_color, float padding, float screen_width, float screen_height, float x_pos, float y_pos, float width, float height)
TextField factory function.
Static Public Member Functions inherited from Graphics::UI::TextArea
static std::shared_ptr< TextArea > create (std::shared_ptr< Skin > skin, std::shared_ptr< WrappableText > text, glm::vec4 color, glm::vec4 text_color, float padding, float screen_width, float screen_height, float x_pos, float y_pos, float width, float height)
TextArea factory function.
Static Public Member Functions inherited from Graphics::UI::Area
static std::shared_ptr< Area > create (std::shared_ptr< Skin > skin, glm::vec4 color, float screen_width, float screen_height, float x_pos, float y_pos, float width, float height)
Area factory function.
Static Public Member Functions inherited from Graphics::Renderable
static std::shared_ptr< Renderable > create (const VertexData &vertex_data)
Renderable factory function.
Protected Attributes
const glm::vec4 mouse_over_dim = glm::vec4(0.1, 0.1, 0.1, 0.0)
Protected Attributes inherited from Graphics::Renderable
std::set< Uniform > uniforms
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Additional Inherited Members
Protected Member Functions inherited from Graphics::Renderable
void setUniform (const Uniform &uniform) noexcept
Renderable ()
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Static Protected Member Functions inherited from Graphics::UI::Element
static std::vector< glm::vec3 > generateRect (float screen_width, float screen_height, float x_pos, float y_pos, float width, float height) noexcept
static std::vector< glm::vec2 > basisTexCoords () noexcept
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for text field.
Constructor & Destructor Documentation
Graphics::UI::TextField::TextField (std::shared_ptr< WrappableText > default_text, std::shared_ptr< WrappableText > typed_text, VertexData vertex_data, std::shared_ptr< Skin > skin)
TextField constructor.
Parameters
[in] default_text The default text
[in] typed_text The typed text
[in] vertex_data The vertex data
[in] skin The skin
References Graphics::UI::TextArea::setText().
Member Function Documentation
const std::string Graphics::UI::TextField::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
std::shared_ptr< TextField > Graphics::UI::TextField::create (std::shared_ptr< Skin > skin, std::shared_ptr< WrappableText > default_text, std::shared_ptr< WrappableText > typed_text, glm::vec4 background_color, float padding, float screen_width, float screen_height, float x_pos, float y_pos, float width, float height) static
TextField factory function.
Parameters
[in] skin The skin
[in] default_text The default text
[in] typed_text The typed text
[in] background_color The background color
[in] padding The padding
[in] screen_width The screen width
[in] screen_height The screen height
[in] x_pos The x position
[in] y_pos The y position
[in] width The width
[in] height The height
Returns
{ description_of_the_return_value }
References Graphics::UI::Element::basisTexCoords(), and Graphics::UI::Element::generateRect().
Referenced by generated::getTextFieldModule().
const unsigned long long Graphics::UI::TextField::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Reimplemented from Graphics::UI::TextArea.
void Graphics::UI::TextField::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Graphics::UI::TextArea.
References Events::CHARACTER_TYPED, Graphics::UI::TextArea::handleQueuedEvent(), and onCharacterTyped().
Referenced by onNotifyNow().
void Graphics::UI::TextField::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Graphics::UI::TextArea.
References to_string().
void Graphics::UI::TextField::onCharacterTyped (const unsigned char character) virtual
Referenced by generated::getTextFieldModule(), and handleQueuedEvent().
void Graphics::UI::TextField::onCursorEnter () override virtual
Called when the mosue cursor goes over the element.
Reimplemented from Graphics::UI::TextArea.
References Graphics::UI::Element::getColor(), mouse_over_dim, and Graphics::UI::Element::setColor().
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onCursorLeave () override virtual
Called when the mouse cursor goes off the element.
Reimplemented from Graphics::UI::TextArea.
References Graphics::UI::Element::getColor(), mouse_over_dim, and Graphics::UI::Element::setColor().
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onDestroy () override virtual
Called when the engine is shutting down.
Reimplemented from Graphics::UI::TextArea.
References Graphics::UI::TextArea::onDestroy().
void Graphics::UI::TextField::onKeyDown (const int key) override virtual
Called when a key is pressed while element is in focus.
Parameters
[in] key The key
Reimplemented from Graphics::UI::TextArea.
References Utility::DebugCommandEvent::create(), Component::isActive(), Events::Subject::notifyNow(), and Component::setActive().
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onKeyRepeat (const int key) override virtual
Called when a key is repeated while element is in focus.
Parameters
[in] key The key
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onKeyUp (const int key) override virtual
Called when a key is released while element is in focus.
Parameters
[in] key The key
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onLeftClick () override virtual
Called when element is left clicked.
Reimplemented from Graphics::UI::TextArea.
References Events::Subject::notifyNow(), and Graphics::UI::TextArea::setText().
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onLeftClickRelease () override virtual
Called when element has left click released over it.
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Graphics::UI::TextArea.
References handleQueuedEvent().
void Graphics::UI::TextField::onRightClick () override virtual
Called when element is right clicked.
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onRightClickRelease () override virtual
Called when element has right click released over it.
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onScroll (const glm::dvec2 position_change) override virtual
Called when the mouse wheel is scrolled while element is in focus.
Parameters
[in] position_change The position change
Reimplemented from Graphics::UI::TextArea.
Referenced by generated::getTextFieldModule().
void Graphics::UI::TextField::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Reimplemented from Graphics::UI::TextArea.
References Component::getTransform(), and Graphics::UI::TextArea::onStart().
const bool Graphics::UI::TextField::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Reimplemented from Graphics::UI::TextArea.
References Graphics::UI::TextArea::onUpdate().
const std::string Graphics::UI::TextField::to_string () const noexcept
Returns a string representation of the object.
Returns
String representation of the object.
References Graphics::UI::TextArea::to_string().
Referenced by generated::getTextFieldModule(), and log().
Member Data Documentation
const glm::vec4 Graphics::UI::TextField::mouse_over_dim = glm::vec4(0.1, 0.1, 0.1, 0.0) protected
Referenced by onCursorEnter(), and onCursorLeave().
The documentation for this class was generated from the following files:
src/graphics/ui/text_field.h
src/graphics/ui/text_field.cpp