Nymph Game Engine: Graphics::UI::WrappableText Class Reference
Graphics::UI::WrappableText Class Reference
Class for wrappable text.
#include <wrappable_text.h>
Public Types
enum HorizontalAlignment : unsigned int { LEFT, HCENTER, RIGHT }
Horizontal Alignment Enum.
enum VerticalAlignment : unsigned int { TOP, VCENTER, BOTTOM }
Vertical Alignment Enum.
Public Member Functions
WrappableText ()
Wrappable Text constructor.
void setSize (float width, float height)
Sets the size.
void setLineSpacing (float spacing)
Sets the line spacing.
void setHorizontalAlignment (const HorizontalAlignment &alignment)
Sets the horizontal alignment.
void setVerticalAlignment (const VerticalAlignment &alignment)
Sets the vertical alignment.
virtual void setText (const std::string &text) override
Sets the text string.
const std::string to_string () const noexcept
Returns a string representation of the object.
virtual const std::string className () const noexceptoverride
Returns a string representing the class name.
virtual void onDestroy () override
Called when the engine is shutting down.
virtual void onStart () override
Called when the engine starts and when a new scene is loaded.
virtual const bool onUpdate (const double delta) override
Called every engine loop.
void handleQueuedEvent (std::shared_ptr< Events::Event > event) override
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
void onNotifyNow (std::shared_ptr< Events::Event > event) override
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
virtual const unsigned long long getValueForSorting () const noexceptoverride
Gets the value for sorting.
virtual void log (el::base::type::ostream_t &os) const
Public Member Functions inherited from Graphics::UI::Text
Text ()
Constructor for Text.
void setFont (const std::shared_ptr< Font > font)
Sets the font.
const std::string getText () const noexcept
Gets the text string.
void setColor (const glm::vec4 &color)
Sets the color.
const glm::vec4 getColor () const noexcept
Gets the color.
void setShader (std::shared_ptr< Shader > shader)
Sets the shader.
void setKerning (const float amount) noexcept
Sets the kerning.
const float getKerning () const noexcept
Gets the kerning.
const std::string to_string () const noexcept
Returns a string representation of the object.
Public Member Functions inherited from Component
Component ()
Component constructor.
void setTransform (std::shared_ptr< Transform > transform)
Sets the transform.
std::shared_ptr< Transform > getTransform () const noexcept
Gets the transform.
void setActive (const bool active) noexcept
Sets the component active or inactive.
const bool isActive () const noexcept
Determines if active.
const unsigned int getId () const noexcept
Gets the identifier.
const std::string to_string () const noexcept
Returns a string representation of the object.
const bool operator< (Component &other) noexcept
Operator < using getValueForSorting.
virtual ~Component ()
Destroys the object.
Public Member Functions inherited from Events::Subject
virtual ~Subject ()=default
virtual void notify (std::shared_ptr< Event > event)
notify is used to tell observers of an event.
virtual void notifyNow (std::shared_ptr< Event > event)
notifyNow is used to tell observers of an event as an interrupt.
virtual void addObserver (std::shared_ptr< Observer > observer)
Adds an observer.
virtual void removeObserver (std::shared_ptr< Observer > observer)
Removes an observer.
Public Member Functions inherited from Events::Observer
virtual ~Observer ()
void onNotify (std::shared_ptr< Event > event)
When receiving an event that is non-immediate, onNotify is used. The event is added to the event queue that is processed when processEventQueue is called.
void processEventQueue ()
This should be called once ever loop for every Observer to properly use queued events.
Protected Member Functions
std::vector< std::pair< float, std::vector< Character > > > splitTextIntoLines ()
Protected Member Functions inherited from Graphics::UI::Text
void renderCharacter (const unsigned char character, Transform transform)
Protected Member Functions inherited from Events::Observer
std::shared_ptr< Event > getEvent ()
const bool eventsWaiting () const noexcept
Additional Inherited Members
Protected Attributes inherited from Graphics::UI::Text
std::shared_ptr< Font > font
std::string text
glm::vec4 color
std::shared_ptr< Shader > shader
float kerning
Protected Attributes inherited from Component
std::weak_ptr< Entity > entity
std::shared_ptr< Transform > transform
bool active
unsigned int id
Static Protected Attributes inherited from Component
static unsigned int next_id = 0
Detailed Description
Class for wrappable text.
Member Enumeration Documentation
enum Graphics::UI::WrappableText::HorizontalAlignment : unsigned int
Horizontal Alignment Enum.
Enumerator
LEFT
HCENTER
RIGHT
enum Graphics::UI::WrappableText::VerticalAlignment : unsigned int
Vertical Alignment Enum.
Enumerator
TOP
VCENTER
BOTTOM
Constructor & Destructor Documentation
Graphics::UI::WrappableText::WrappableText ()
Wrappable Text constructor.
Member Function Documentation
const std::string Graphics::UI::WrappableText::className () const override virtual noexcept
Returns a string representing the class name.
Returns
The class name
Reimplemented from Graphics::UI::Text.
Referenced by generated::getWrappableTextModule().
const unsigned long long Graphics::UI::WrappableText::getValueForSorting () const override virtual noexcept
Gets the value for sorting.
Returns
The value for sorting.
Reimplemented from Graphics::UI::Text.
void Graphics::UI::WrappableText::handleQueuedEvent (std::shared_ptr< Events::Event > event) override virtual
HandleQueuedEvent allows derived classes to define behaviour for when queuedEvents are received.
Parameters
[in] event The event
Reimplemented from Graphics::UI::Text.
void Graphics::UI::WrappableText::log (el::base::type::ostream_t & os) const virtual
Reimplemented from Graphics::UI::Text.
References to_string().
void Graphics::UI::WrappableText::onDestroy () override virtual
Called when the engine is shutting down.
Reimplemented from Graphics::UI::Text.
void Graphics::UI::WrappableText::onNotifyNow (std::shared_ptr< Events::Event > event) override virtual
When receiving an event that is immediate, onNotifyNow is used. It acts as an interrupt to make sure the object is notified before another engine loop. This is pure virtual and is implemented on a case by case basis in derived classes.
Parameters
[in] event The event
Reimplemented from Graphics::UI::Text.
void Graphics::UI::WrappableText::onStart () override virtual
Called when the engine starts and when a new scene is loaded.
Reimplemented from Graphics::UI::Text.
const bool Graphics::UI::WrappableText::onUpdate (const double delta) override virtual
Called every engine loop.
Parameters
[in] delta The delta
Returns
true if active
Reimplemented from Graphics::UI::Text.
References Graphics::UI::Text::color, Component::isActive(), Graphics::UI::Text::renderCharacter(), Graphics::Uniform::setData(), Graphics::UI::Text::shader, and Component::transform.
void Graphics::UI::WrappableText::setHorizontalAlignment (const HorizontalAlignment & alignment)
Sets the horizontal alignment.
Parameters
[in] alignment The alignment
Referenced by generated::getWrappableTextModule().
void Graphics::UI::WrappableText::setLineSpacing (float spacing)
Sets the line spacing.
Parameters
[in] spacing The spacing
Referenced by generated::getWrappableTextModule().
void Graphics::UI::WrappableText::setSize (float width, float height)
Sets the size.
Parameters
[in] width The width
[in] height The height
Referenced by generated::getWrappableTextModule().
void Graphics::UI::WrappableText::setText (const std::string & text) override virtual
Sets the text string.
Parameters
[in] text The text string
Reimplemented from Graphics::UI::Text.
References Graphics::UI::Text::font, Transform::getAbsoluteTranslation(), Graphics::UI::Text::kerning, splitTextIntoLines(), Graphics::UI::Text::text, and Transform::translate().
Referenced by generated::getWrappableTextModule().
void Graphics::UI::WrappableText::setVerticalAlignment (const VerticalAlignment & alignment)
Sets the vertical alignment.
Parameters
[in] alignment The alignment
Referenced by generated::getWrappableTextModule().
std::vector< std::pair< float, std::vector< Character > > > Graphics::UI::WrappableText::splitTextIntoLines () protected
References Graphics::UI::Text::font, Graphics::UI::Text::kerning, and Graphics::UI::Text::text.
Referenced by setText().
const std::string Graphics::UI::WrappableText::to_string () const noexcept
Returns a string representation of the object.
Returns
String representation of the object.
References Graphics::UI::Text::to_string().
Referenced by generated::getWrappableTextModule(), and log().
The documentation for this class was generated from the following files:
src/graphics/ui/wrappable_text.h
src/graphics/ui/wrappable_text.cpp